/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-14 04:52:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class privacyPolicy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/board/../common/top.jsp", Long.valueOf(1623644440720L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/bottom.jsp", Long.valueOf(1623646288743L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하단_개인정보처리방침</title>\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap-4.3.1.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap-4.3.1.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* ----------스크롤시 하단아이콘  보이기 --------------------------------------------------------------------- */\r\n");
      out.write("\r\n");
      out.write(".bottomNav {position: fixed; font-size:50px; color: #11BBFF;}\r\n");
      out.write(".bottomNav {bottom: -90px;  transition:bottom .2s;}\r\n");
      out.write(".bottomNav.show {bottom: 0; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	<div id=\"main-container\" class=\"container\">\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member) session.getAttribute("loginUser"); 
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>메인페이지</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 메인이미지슬라이드 -------------->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\" />\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("<!-- --------------------- -->\r\n");
      out.write("<style>\r\n");
      out.write("/*상단 관련 스타일*/\r\n");
      out.write("/*검색창*/\r\n");
      out.write(".btn-outline-secondary {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:hover {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #FBA481;\r\n");
      out.write("	border-color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:focus, .btn-outline-secondary.focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active, .show>.btn-outline-secondary.dropdown-toggle\r\n");
      out.write("	{\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active:focus,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active:focus,\r\n");
      out.write("	.show>.btn-outline-secondary.dropdown-toggle:focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("/*아이콘 색변경*/\r\n");
      out.write(".i-plain {\r\n");
      out.write("	color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".i-plain:hover {\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("/*메뉴버튼*/\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 100%;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   display: none;\r\n");
      out.write("   float: left;\r\n");
      out.write("   min-width: 250px;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   background-color: #fff;\r\n");
      out.write("   background-clip: padding-box;\r\n");
      out.write("   border: 2px solid rgba(17, 187, 255, 1);\r\n");
      out.write("   border-radius: 0.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("   color: #11bbff;\r\n");
      out.write("}\r\n");
      out.write(".button1{\r\n");
      out.write("	border: 1px solid rgb(17, 187, 255);\r\n");
      out.write("	background-color: rgb(17, 187, 255);\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ----------------아이콘 호버시 색 바꾸기------------------- */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".i-side {\r\n");
      out.write("     color: #fff;\r\n");
      out.write(" }\r\n");
      out.write(".i-side:hover {\r\n");
      out.write("     color: #FBA481;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(".side-nav {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".side-nav:hover{\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("	text-decoration:none !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- 1행 -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<!-- 상단 광고 -->\r\n");
      out.write("			<div class=\"col-12\" id=\"top-bar\" onclick=\"location.href='프로모션.html';\"\r\n");
      out.write("				style=\"background: #11BBFF; text-align: center; cursor: pointer; line-height: 30px; font-size: 14px; font-weight: bold; color: white;\">\r\n");
      out.write("				더운 여름을 시원하게! 여름 맞이 프로모션으로 함께 떠나요!</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 2행 -->\r\n");
      out.write("		<div class=\"row\" id=\"secondRow\">\r\n");
      out.write("			<!-- 로고  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<div id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/mainPage.me';\"\r\n");
      out.write("					style=\"color: #11BBFF; font-size: 32px; text-align: center; vertical-align: middle; margin-top: 16px; font-weight: bold; cursor: pointer; color: #11BBFF;\">\r\n");
      out.write("					<i class=\"bi bi-house\" style=\"font-size: 37px;\"></i>다나와방\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 검색창  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<!-- 검색 아이콘  -->\r\n");
      out.write("				<div style=\"margin-top: 30px;\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력해주세요\"\r\n");
      out.write("						style=\"font-size: 13px; border-color: #11BBFF; margin-left: 30px;\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<button class=\"btn btn-outline-secondary\" type=\"submit\"\r\n");
      out.write("					id=\"main-search\" style=\"font-size: 14px; margin-top: 30px;\">검색</button>\r\n");
      out.write("			</div>		\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("			<!-- 로그인/회원가입 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"login\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그인/회원가입</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("			<!-- 로그아웃 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"logout\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그아웃</div>\r\n");
      out.write("			</div>	\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			<!-- 마이페이지 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 42px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("ADMIN")) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/adminMember.me';\"></i>\r\n");
      out.write("			");
 } else {
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myOrder.me';\"></i>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 고객센터 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 20px; cursor: pointer; font-size: 37px;\">\r\n");
      out.write("				<i class=\"bi bi-headset i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 장바구니 아이콘 -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 38px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("USER")) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/????????';\"></i>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 3행 -->\r\n");
      out.write("		<!-- 메뉴아이콘 -->\r\n");
      out.write("		<div class=\"row\" id=\"thirdRow\"\r\n");
      out.write("			style=\"text-align: center; margin-top: 15px;\">\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<div class=\"dropdown\" style=\"margin-top: -10px;\">\r\n");
      out.write("					<a class=\"btn-group-vertical\" href=\"#\" role=\"button\"\r\n");
      out.write("						id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"bi bi-list i-plain\"\r\n");
      out.write("						style=\"font-size: 35px;\"></i></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\"\r\n");
      out.write("						style=\"text-align: center; font-weight: bold;\">\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">6평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/6평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">8평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/8평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">10평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/10평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">12평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/12평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">14평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/14평.png\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 스토어 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='스토어페이지(완).html';\"\r\n");
      out.write("				style=\"font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">스토어</div>\r\n");
      out.write("			<!-- 셀프가이드 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='셀프가이드(완).html';\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">셀프가이드</div>\r\n");
      out.write("			<!-- 프로모션 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='프로모션(완).html';\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">프로모션</div>\r\n");
      out.write("			<div class=\"col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 구분선 -->\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"margin-top: 20px; width: 100%; border-bottom: 2px solid #11BBFF\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 15px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- ------------------------스크립트 공간 ----------------------- -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- 상단 스크립트 -->\r\n");
      out.write("	<script>\r\n");
      out.write("	//2행 로고\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#logo').hover(function() {\r\n");
      out.write("			$(this).css('font-size', '34px');\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css('font-size', '32px');\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로그인\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#login').hover(function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#FBA481',\r\n");
      out.write("				'border-color' : '#FBA481'\r\n");
      out.write("			});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#11BBFF',\r\n");
      out.write("				'border-color' : '#11BBFF'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//3행\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#thirdRow').children().hover(function() {\r\n");
      out.write("			$(this).css('color', '#FBA481');\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css('color', '#11BBFF');\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 필요한 외부 script -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("\r\n");
      out.write("			<!-- 개인정보처리방침제목 -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- 여백 -->\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("				<!-- 개인정보처리방침 -->\r\n");
      out.write("				<div class=\"col\"\r\n");
      out.write("					style=\"text-align: center; font-size: 25px; font-weight: bold; color: rgb(17, 187, 255);\">개인정보처리방침</div>\r\n");
      out.write("				<!-- 여백 -->\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 행 사이 빈공간-->\r\n");
      out.write("			<div class=\"row\" style=\"margin-top: 10px;\"></div>\r\n");
      out.write("			<!-- 행 사이 빈공간-->\r\n");
      out.write("			<div class=\"row\" style=\"margin-top: 30px;\"></div>\r\n");
      out.write("			<!-- 본문내용 -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 overflow-auto\" style=\"font-size: 12px;\">\r\n");
      out.write("					((주)다나와방(이하 \"회사\"라 합니다)은 회사가 제공하는 서비스 회원의 개인정보보호를 매우 중요시하며, 『정보통신망\r\n");
      out.write("					이용촉진 및 정보보호 등에 관한 법률』등 개인정보와 관련된 법령 상의 개인정보보호규정을 준수하고 있습니다. 회사는 아래와\r\n");
      out.write("					같이 개인정보처리방침을 명시하여 회원이 회사에 제공한 개인정보가 어떠한 용도와 방식으로 이용되고 있으며 개인정보보호를\r\n");
      out.write("					위해 어떠한 조치를 취하는지 알려드립니다. 회사의 서비스 개인정보처리방침은 정부의 법률 및 지침의 변경과 당사의 약관 및\r\n");
      out.write("					내부 정책에 따라 변경될 수 있으며 이를 개정하는 경우 회사는 변경사항에 대하여 즉시 서비스 화면에 게시합니다.\r\n");
      out.write("					회원님께서는 사이트 방문 시 수시로 확인하시기 바랍니다.<br>\r\n");
      out.write("					<!-- 본문내용1 -->\r\n");
      out.write("					<br> <b>1. 다나와방은 이용하는 서비스의 형태에 따라 다음과 같은 개인정보를 수집 및\r\n");
      out.write("						이용∙제공∙파기하고 있습니다.</b><br> <br> ① 개인정보의 수집 ∙ 이용 목적 및 항목 <br>회사가\r\n");
      out.write("					제공하는 서비스는 별도의 회원가입 절차 없이 자유롭게 컨텐츠에 접근할 수 있습니다. 회사의 회원제 서비스 이용을 위해\r\n");
      out.write("					수집 ∙ 이용하는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 목적 변경 시 별도의 동의를 받는 등 필요한\r\n");
      out.write("					조치를 이행합니다. <br> <br>② 개인정보 수집 방법<br>1) 회원가입 및 서비스 이용\r\n");
      out.write("					과정에서 이용자가 개인정보 수집에 대해 동의를 하고 직접 정보를 입력하는 경우, 해당 개인정보를 수집합니다.<br>2)\r\n");
      out.write("					고객센터를 통한 상담 과정에서 웹 페이지, 메일, 팩스, 전화 등을 통해 이용자의 개인정보가 수집될 수 있습니다. <br>3)\r\n");
      out.write("					회사와 제휴한 외부 기업이나 단체로부터 개인정보를 제공받을 수 있으며, 이러한 경우에는 제휴사에서 이용자에게 개인정보\r\n");
      out.write("					제공 동의를 받은 후 수집합니다. <br> <br>③ 개인정보 보유 ∙ 이용 기간<br>1)\r\n");
      out.write("					회사는 이용자로부터 개인정보 수집 시에 동의 받은 보유 · 이용기간 내에서 개인정보를 처리·보유합니다.<br>\r\n");
      out.write("					- 회원 정보: 회원탈퇴 후 1개월 일까지 <br> - 비회원 정보: 업무 목적 달성 시까지 <br>\r\n");
      out.write("					- 서비스 이용에 따른 채권·채무관계 정산 시까지<br> 2) 1 년 간 회원의 서비스 이용 기록이 없는 경우,\r\n");
      out.write("					『정보통신망 이용촉진 및 정보보호등에 관한 법률』 제 29 조에 근거하여 회원에게 사전 통지하고, 별도 보관합니다. <br>3)\r\n");
      out.write("					회원에서 탈퇴한 후 회원 재가입, 임의해지 등을 반복적으로 행하여 회사가 제공하는 할인쿠폰, 이벤트 혜택 등으로 경제상의\r\n");
      out.write("					이익을 취하거나 이 과정에서 명의를 무단으로 사용하는 편법과 불법행위를 하는 회원을 차단 하고자 회원 탈퇴 후 1개월\r\n");
      out.write("					동안 보관합니다. <br>4) 단, 전자상거래 등에서의 소비자보호에 관한 법률 등 관련 법령의 규정에 따라 거래\r\n");
      out.write("					관계 확인을 위해 개인정보를 일정기간 보유 할 수 있습니다.<br> <br>\r\n");
      out.write("					<!-- 본문내용2 -->\r\n");
      out.write("					<b>2. 서비스의 제공 또는 법령에 정해진 책임의 준수를 위하여 회사가 보관하고 있는 개인정보가 제3자에게 수집\r\n");
      out.write("						목적 범위 내에서 제공될 수 있습니다.</b><br> <br> ① 회사는 이용자의 개인정보를 명시한 범위\r\n");
      out.write("					내에서만 처리하며, 정보주체의 동의, 법률의 특별한 규정에 해당하는 경우에만 개인정보를 제 3 자에게 제공합니다.<br>\r\n");
      out.write("					<br> ②회사는 다음과 같이 개인정보를 제 3 자에게 제공하고 있습니다.<br> <br> <b>3.\r\n");
      out.write("						회사는 서비스 향상과 효과적인 업무처리를 위하여 다음과 같이 개인정보를 처리 위탁하고 있습니다.</b><br> <br>①\r\n");
      out.write("					회사는 원활하고 향상된 서비스를 위하여 개인정보 처리를 타인에게 위탁할 수 있습니다. 이 경우 회사는 사전에 다음 각\r\n");
      out.write("					호의 사항 모두를 이용자에게 미리 알리고 동의를 받습니다. <br> (1) 개인정보 처리위탁을 받는 자 <br>\r\n");
      out.write("					(2) 개인정보 처리위탁을 하는 업무의 내용 <br> <br>② 회사는 개인정보의 처리와 관련하여\r\n");
      out.write("					아래와 같이 업무를 위탁하고 있으며, 관계법령에 따라 위탁 계약 시 개인정보가 안전하게 관리될 수 있도록 필요한 조치를\r\n");
      out.write("					하고 있습니다. 회사는 위탁 계약 시 수탁자의 개인정보 보호조치 능력을 고려하고, 개인정보의 안전한 관리 및 파기 등\r\n");
      out.write("					수탁자의 의무 이행 여부를 주기적으로 확인합니다. 또한 위탁처리하는 정보는 원활한 서비스를 제공하기 위하여 필요한\r\n");
      out.write("					최소한의 정보에 국한됩니다. <br> <br> <b>4. 회사는 이용자에게 다른 회사의 웹사이트\r\n");
      out.write("						또는 자료에 대한 링크를 제공할 수 있습니다.</b><br> <br> 회사가 이용자에게 다른 회사의 웹사이트\r\n");
      out.write("					또는 자료에 대한 링크를 제공하는 경우, 회사는 외부사이트 및 자료에 대한 아무런 통제권이 없으므로 그로부터 제공받는\r\n");
      out.write("					서비스나 자료의 유용성에 대해 책임질 수 없으며 보증할 수 없습니다. 회사가 포함하고 있는 링크를 클릭(click)하여\r\n");
      out.write("					타사이트(site)의 페이지로 옮겨 갈 경우 해당 사이트의 개인정보보호정책은 회사와 무관하므로 새로 방문한 사이트의\r\n");
      out.write("					정책을 검토해보시기 바랍니다.<br> <br> <b>5. 이용자 및 법정대리인은 아래와 같은\r\n");
      out.write("						권리를 행사할 수 있습니다.</b> <br> <br>① 이용자 및 법정대리인은 언제든지 수집 정보에 대하여\r\n");
      out.write("					수정, 동의철회, 삭제 등을 요청하실 수 있습니다. 다만, 동의 철회․삭제시 서비스의 일부 또는 전부 이용이 제한될 수\r\n");
      out.write("					있습니다.<br> <br>② (조회/수정 및 정정) 홈페이지에서 ‘마이홈>설정>회원정보수정’ 메뉴 또는\r\n");
      out.write("					1:1 상담을 이용하여 처리할 수 있습니다. 처리가 완료될 때까지 해당 정보를 이용하거나 타인에게 제공하지 않을\r\n");
      out.write("					것입니다. 또한 합리적인 사유로 잘못된 개인정보를 제3자에게 이미 제공한 경우, 정정 처리의 결과를 지체 없이 제3자에게\r\n");
      out.write("					통지하여 정정하도록 조치합니다.<br> <br>③ (동의 철회/삭제) 1:1 상담을 이용하여 수집\r\n");
      out.write("					정보에 대한 동의 철회 및 삭제를 요청하실 수 있습니다. 다만, 수집정보에 대한 동의 철회․삭제시 서비스의 일부 또는\r\n");
      out.write("					전부 이용이 제한될 수 있으며, 다른 법령에 따라 수집하는 정보의 경우에는 동의 철회가 어려울 수 있습니다.<br>\r\n");
      out.write("					<br>④ (회원 탈퇴) 홈페이지의 ‘마이홈>설정>회원정보수정>회원탈퇴’ 메뉴를 이용하여 편리하게 직접 탈퇴를\r\n");
      out.write("					진행하시거나, 1:1상담을 통하여 진행할 수 있습니다.<br> <br>⑤ (서비스 재이용) ‘아이디\r\n");
      out.write("					찾기’를 통하여 미이용자 여부를 확인할 수 있으며, 반드시 비밀번호를 변경하신 후 계정 재이용이 가능합니다. 문의사항은\r\n");
      out.write("					고객센터 1670-0876을 이용하시기 바랍니다.<br> <br>⑥ (상담/문의) 회사는 개인정보의\r\n");
      out.write("					수집 및 이용 목적에 따라 이용자와 상담원 간의 통화내용을 녹음할 수 있으며 고객센터를 통한 소비자 상담/문의 시 녹음\r\n");
      out.write("					등에 대한 안내는 고객센터 상담 전 안내 멘트를 통해 확인하실 수 있습니다. <br> <br> <b>6.\r\n");
      out.write("						자동 수집되는 개인정보 및 거부에 관한 사항은 다음과 같습니다.</b><br> <br>회사는 이용자의 정보를\r\n");
      out.write("					수시로 저장하고 찾아내는 쿠키(cookie) 등을 운용합니다. 쿠키는 웹사이트가 이용자의 컴퓨터 브라우저에 보내는 아주\r\n");
      out.write("					작은 텍스트 파일로 이용자의 컴퓨터 하드디스크에 저장됩니다.<br> <br>① 쿠키의 사용 목적<br>-\r\n");
      out.write("					회원과 비회원의 접속 빈도나 방문 시간 등의 분석, 이용 형태 및 관심분야 파악, 자취 추적, 각종 이벤트 참여 정도,\r\n");
      out.write("					방문 횟수 파악 등을 통한 타겟 마케팅 등 개인별 맞춤 서비스를 제공하기 위해 쿠키를 사용 합니다.<br> <br>②\r\n");
      out.write("					쿠키의 설치, 운영과 거부<br>- 이용자는 쿠키 설치에 대한 선택권을 가지고 있으며, 언제든지 이러한 쿠키의\r\n");
      out.write("					저장을 거부하거나 삭제할 수 있습니다.<br>- 쿠키의 설정은 웹브라우저별 옵션 선택을 통해 ①모든 쿠키를\r\n");
      out.write("					허용, ②쿠키가 저장될 때 마다 확인, ③모든 쿠키의 저장을 거부 할 수 있습니다.<br>- 이러한 쿠키의 설정\r\n");
      out.write("					방법은 웹브라우저에 따라 차이가 있으므로, 자세한 사항은 각 브라우저별 도움말을 참고해 주시기 바랍니다.<br>-\r\n");
      out.write("					Internet Explorer : 도구 메뉴 선택 > 인터넷 옵션 선택 > 개인정보 탭 클릭 > 개인정보처리 수준 설정<br>-\r\n");
      out.write("					Chrome : 설정 메뉴 선택 > 고급 설정 표시 선택 > 개인정보-콘텐츠 설정 선택 > 쿠키 수준 설정<br>-\r\n");
      out.write("					firefox : 옵션 메뉴 선택 > 개인정보 선택 > 방문기록-사용자 정의 설정 > 쿠키 수준 설정 <br>-\r\n");
      out.write("					safari : 환경설정 메뉴 선택 > 개인정보 탭 선택 > 쿠키 및 웹 사이트 데이터 수준 설정<br>- 단,\r\n");
      out.write("					쿠키의 저장을 거부하였을 경우에는 로그인이 필요한 서비스 등 일부 서비스 이용에 어려움이 있을 수 있습니다.<br>\r\n");
      out.write("					<br> <b>7. 맞춤형 광고</b><br> <br> 고객에게 맞춤형 광고를 제공하기 위하여\r\n");
      out.write("					회사는 웹 브라우저에서는 ‘쿠키’, 모바일 앱에서는 광고식별자(ADID)를 수집하여 사용합니다. 회사는 쿠키 및\r\n");
      out.write("					광고식별자를 통해 고객의 서비스 사용 이력을 자동으로 수집하고 이를 활용하여 고객 맞춤 광고를 진행합니다. 회사에서\r\n");
      out.write("					수집하는 쿠키 및 광고식별자는 다른 개인정보와 연계되지 않으며 개인을 식별하지 않습니다. 사용자는 언제든지 이러한 맞춤형\r\n");
      out.write("					광고 수신을 거부할 수 있습니다.<br> <br> <b>8. 회사는 이용자들의 개인정보를\r\n");
      out.write("						처리함에 있어 개인정보의 기술적/관리적 보호 대책을 마련하여 정보보호를 위해 노력하고 있습니다.</b><br> <br>\r\n");
      out.write("					회사는 이용자들의 개인정보를 처리함에 있어 개인정보가 분실, 도난, 유출, 변조 또는 훼손되지 않도록 안전성 확보를\r\n");
      out.write("					위하여 다음과 같은 기술적/관리적 보호대책을 강구하고 있습니다.<br> <br> ① 비밀번호의 암호화<br>-\r\n");
      out.write("					이용자의 비밀번호는 일방향 암호화하여 저장 및 관리되고 있으며, 개인정보의 확인 및 변경은 비밀번호를 알고 있는 본인에\r\n");
      out.write("					의해서만 가능합니다.<br> <br>② 해킹 등에 대비한 대책<br>- 회사는 해킹이나\r\n");
      out.write("					바이러스 등 회사 정보통신망 침입에 의한 이용자 개인정보의 분실, 도난, 유출, 변조 또는 훼손 등 피해 방지를 위해\r\n");
      out.write("					침입탐지 및 침입차단 시스템을 24시간 가동하고 있으며, 만일의 사태에 대비하여 모든 침입탐지 시스템과 침입차단 시스템은\r\n");
      out.write("					이중화로 구성하여 운영하고 있습니다.<br>- 개인정보의 훼손 피해에 대비하여 중요한 데이터를 주기적으로\r\n");
      out.write("					백업하고 있으며, 백신 프로그램을 이용하여 개인정보나 중요한 데이터의 유출 방지를 위해 노력하고 있습니다.<br>-\r\n");
      out.write("					민감한 개인정보는 정보통신망을 통해 주고받는 과정에서 암호화 통신을 적용하여 개인정보를 안전하게 전송할 수 있도록 하고\r\n");
      out.write("					있습니다.<br>- 이 외에도 보안 시스템 도입 및 전문인력 확충 등 보안성 확보를 위해 지속적으로 노력하고\r\n");
      out.write("					있습니다.<br> <br>③ 개인정보 처리자의 최소화 및 주기적인 교육<br>- 회사의\r\n");
      out.write("					개인정보 관련 처리자는 담당자로 한정하여 개인정보 처리자를 최소화 하고 있으며, 퇴직 및 직무변경 등 인사이동이 있는\r\n");
      out.write("					경우 지체 없이 권한을 변경, 말소 하여 개인정보 접근 권한을 통제 하고 있습니다.<br>- 개인정보 처리자에\r\n");
      out.write("					대해 주기적으로 교육을 진행하여 개인정보보호의 중요성을 인식시키고, 안전하게 관리 할 수 있도록 최선의 노력을 다하고\r\n");
      out.write("					있습니다.<br> <br> <b>9. 이용자의 의무</b> <br> <br>①\r\n");
      out.write("					이용자는 본인의 개인정보를 안전하게 지키기 위해 개인정보보호에 관한 법률을 준수할 의무가 있습니다.<br> <br>\r\n");
      out.write("					② 이용자는 자신의 개인정보를 안전하게 보호할 의무가 있으며, 회사는 이용자 개인의 부주의로 인해 발생된 일에 대해서는\r\n");
      out.write("					책임을 지지 않습니다. 따라서 이용자는 자신의 개인정보보호를 위하여 ID 및 비밀번호를 철저히 관리하고 주기적으로\r\n");
      out.write("					변경하는 등의 최선의 노력을 다할 의무가 있습니다.<br> <br>③ 이용자는 본인의 개인정보를 최신의\r\n");
      out.write("					상태로 정확하게 입력하고 유지할 의무가 있습니다. 이용자의 부정확한 정보 입력으로 인하여 발생하는 문제의 책임은 이용자\r\n");
      out.write("					본인에게 있습니다.<br> <br>④ 이용자는 타인의 개인정보를 도용하여 회원가입 또는 서비스 이용 시\r\n");
      out.write("					회원자격 상실과 함께 개인정보에 관한 법률에 의거하여 처벌될 수 있습니다.<br> <br>⑤ 이용자는\r\n");
      out.write("					타인의 개인정보를 침해하거나 유출하지 않을 의무도 가지고 있습니다. 서비스 이용 중 다른 이용자에 대해 알게 된\r\n");
      out.write("					개인정보를 언급하거나, 유출할 경우 개인정보 관련 법령에 의거하여 처벌될 수 있습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>10. 개인정보 처리방침 변경에 관한 정책은 다음과 같습니다.</b><br>\r\n");
      out.write("					<br> 이 개인정보 처리방침은 시행일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이\r\n");
      out.write("					있는 경우에는 변경사항의 시행 7일 전부터 공지사항을 통하여 고지할 것입니다. 또한 관련 법령이나 회사 정책의 변경으로\r\n");
      out.write("					불가피하게 처리방침을 변경해야 하는 경우, 웹사이트 공지사항을 통해 빠르게 알려드리고 있으니 참고하여 주시기 바랍니다.\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 40px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 하단 -->\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12\" onclick=\"location.href='고객센터.html';\"\r\n");
      out.write("				style=\"color: black; line-height: 30px; font-size: 22px; font-weight: bold; cursor: pointer;\">\r\n");
      out.write("				고객센터 : 1555-5551</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12\" style=\"color: black; font-size: 13px;\">평일\r\n");
      out.write("				09:00 ~ 18:00 (주말 & 공휴일 제외)</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 20px;\"></div>\r\n");
      out.write("		<div class=\"row\" style=\"text-align: center;\">\r\n");
      out.write("			<div class=\"col-1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/introduction.me';\"\r\n");
      out.write("				style=\"color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">회사소개</div>\r\n");
      out.write("			<div class=\"col-1\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/accessTerms.me';\"\r\n");
      out.write("				style=\"color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">이용약관</div>\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/privacyPolicy.me';\"\r\n");
      out.write("				style=\"color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">개인정보처리방침</div>\r\n");
      out.write("			<div class=\"col-1\" onclick=\"location.href='공지사항.html';\"\r\n");
      out.write("				style=\"color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">공지사항</div>\r\n");
      out.write("			<div class=\"col-1\" onclick=\"location.href='고객센터.html';\"\r\n");
      out.write("				style=\"color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">고객센터</div>\r\n");
      out.write("			<div class=\"col-6\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 10px;\"></div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-12\" style=\"font-size: 12px;\">\r\n");
      out.write("				<p>\r\n");
      out.write("					상호명 : (주)다나와방 / 이메일 : danawabang@danawabang.com / 대표이사 : 박신우 /\r\n");
      out.write("					사업자등록번호 : 999-88-77777 / 통신판매업신고번호 : 제2021-서울역삼-0215호<br> 주소 :\r\n");
      out.write("					서울 역삼구 역삼대로56길 6 타워팰리스타워 31층 <br> Copyright 2021. danawabang,\r\n");
      out.write("					Co., Ltd. All rights reserved\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	<!-- 탭 하면 맨위로 올라가는 버튼 -->				 \r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-10\"></div>\r\n");
      out.write("		<div class=\"col-1\" style=\"float-right\">\r\n");
      out.write("			<i class=\"bi bi-arrow-up-circle-fill bottomNav i-plain\" \r\n");
      out.write("			style=\"cursor:pointer;\" onclick=\"window.scrollTo(0,0);\" ></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-1\">\r\n");
      out.write("			<i class=\"bi bi-whatsapp bottomNav i-plain\" style=\"cursor:pointer;\" ></i>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 스크롤 시 하단 아이콘 보이기-------------------------------------------- -->\r\n");
      out.write("	<script>\r\n");
      out.write("	//Javascript\r\n");
      out.write("	var lastScrollTop = 0;\r\n");
      out.write("	var delta = 10;\r\n");
      out.write("	var fixBox = document.querySelector('.bottomNav');\r\n");
      out.write("	var fixBoxHeight = fixBox.offsetHeight;\r\n");
      out.write("	var didScroll;\r\n");
      out.write("	//스크롤 이벤트 \r\n");
      out.write("	window.onscroll = function(e) {\r\n");
      out.write("	    didScroll = true;\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	//0.25초마다 스크롤 여부 체크하여 스크롤 중이면 hasScrolled() 호출\r\n");
      out.write("	setInterval(function(){\r\n");
      out.write("	    if(didScroll){\r\n");
      out.write("	        hasScrolled();\r\n");
      out.write("	        didScroll = false;\r\n");
      out.write("	    }\r\n");
      out.write("	}, 250);\r\n");
      out.write("\r\n");
      out.write("	function hasScrolled(){\r\n");
      out.write("	    var nowScrollTop = window.scrollY;\r\n");
      out.write("	    if(Math.abs(lastScrollTop - nowScrollTop) <= delta){\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(nowScrollTop > lastScrollTop && nowScrollTop > fixBoxHeight){\r\n");
      out.write("	        //Scroll down\r\n");
      out.write("	        fixBox.classList.add('show');\r\n");
      out.write("	    }else{\r\n");
      out.write("	        if(nowScrollTop + window.innerHeight < document.body.offsetHeight){\r\n");
      out.write("	            //Scroll up\r\n");
      out.write("	            fixBox.classList.remove('show');\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	    lastScrollTop = nowScrollTop;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
