UPDATE MEMBER SET MEMBER_PASSWORD = 'C3rH6IVHK9qovLAPXXHpNnhoqEd6O7xYOhiJCT7LIQKic/txFNm/b+1jbXj9plKqLkuE1XeIUsJPn0mpwz47OA==' WHERE MEMBER_ID = 'Any97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'tGjTNzCggzhEIPEuOLgn5ly/FDZqZMXaZoWn1Da6VhDKCSskMaGK9mUqwnehK+HIbSXsdmqfSlkw71Mm3rf78A==' WHERE MEMBER_ID = 'Clair97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'ognwQV588rsNOXClZhrdl+ZMnip+q9vsqObzPAOYiRsq+sGO4sa9CH4B7L728T/c2xbUIzHSH7XMokJ2x7qP2w==' WHERE MEMBER_ID = 'Reinwald97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '6BBncOlQ9jLURZ2e5JXIyX0ayHY9bVO0ewRTWNCKovplLN00RBLoJfmtHz8ttBqUqckl2a2THM4sJYCnKt16Gw==' WHERE MEMBER_ID = 'Etan97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kdqFuq6QWqsxyOYU9hoVfTDFUDJjlV5iJNYwmg3rd9Wc+a1xpG73ZhxlJGJJWkoljpDmZtMXVTqKIAVdeP/3kQ==' WHERE MEMBER_ID = 'Sylvester97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'g8EL/9cg/tvsrJVl3+YN4/6hgPcocp9WTpbYqsT/DiWraLBQFBnT3ybzy7KhzEiZNGPeu9BCLVXu9cUEG5KXPg==' WHERE MEMBER_ID = 'Gabie97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '+BwxOXxCiDw1M/PZs3AiQOlLJRFhdyEpNG7Ipyw4mPgg/eiuI0NpWs4Ijepiymiqq3+sJEoXdQzgRG+wuSvLaQ==' WHERE MEMBER_ID = 'Burch97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'b5Iy0V37dQf4swdcSHvBKDO+G2RYzbKW3l8SBsq7VdvEscPHTJFf2zAkWJCQVOg56VM2QuZwcjygiYPob088Zg==' WHERE MEMBER_ID = 'Willey97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'CSEwvbO49Hcy5TNhscskChH2Qy80UeYpuiKqlZtwyGiCcCNgPhNVSOwkiirRv17iD5P9u9oPOecmguT5xBDubg==' WHERE MEMBER_ID = 'Noel97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'B2CmXtpLUCHmAxljPqxmM3IIYD8Yg0y/bAg3Pgp58Bq3BPI+/JatqVb5aV+pFTNphMetosS1Vmd27GyFEwXWKg==' WHERE MEMBER_ID = 'Tobe97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'BryTYiE2WB/4JyuqrlAGJoAQW0e686+P3l02dyjeVex11IkAW8UDHzc6gZ+n5NldgHngML1ELSdghJmhI+ICIg==' WHERE MEMBER_ID = 'Red97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'zJeAxVrEZHrqVn532Xe+YHe6PqZgCGpX0ec/ojj59k4CIwZBiaoRvningXa199LbT7/OgjkaK2eaMUhbgD+E4A==' WHERE MEMBER_ID = 'Tarrance97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'jDlkhsoZmP7yae3usP+D23Ift5ZMwYeXNaT25bamiqH9p3jdsz8CXoUsMVAbvvmsb5fFfR447oLZRpa7Il6QhA==' WHERE MEMBER_ID = 'Marcel97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'd3LPc5UKVVndgrYZWe74EkxGcPyTbTNVBlAZCilPpCMbS1R1kXtwC3xlGsSi+8I4Bqgl1WcJkzgbVzCJH6hRnw==' WHERE MEMBER_ID = 'Phillip97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '2f82VDtz9chm0BBE8qvJbTrLPTpvNIcKZUK8El4psIbjn/Cdr5I7u5/FLT0iORMbG1mIFPiU7qWdwgfwIF+V5Q==' WHERE MEMBER_ID = 'Zed97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '9olxI1iE+Oov1v4rJlj9ySIyh16VL7Slo75/8vNrcfZkQgOWX2Mav8JpliSWkZSRz4bU1qf9BEXgtTNEfTuh4Q==' WHERE MEMBER_ID = 'Kevin97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'TcBLO6epZXvG4/95KoVynO5WrIRoXHc/lwmYreln2Mq1B/ORomYKAELn9+AZJPGjPDiowZQbrOXOe0dvvAvmsg==' WHERE MEMBER_ID = 'Artus97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '6iRt5GxHZeI2GFapcvEGH+STVnUm17uhrigc55aQwA2rUfFyddJq9DwYQ/C+7gWN+l3ksHelG0y2vX6QX44omA==' WHERE MEMBER_ID = 'Erroll97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VOyN8pex1P1g+zS5eBkZFd7Ljq4dnNZVULyU+sZ6QsScutdmRo+5bIt+t5EZNM6guY9TJJneimMvTkTY/0F9Ng==' WHERE MEMBER_ID = 'Gerik97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Lm984rtcOKs/mzEqRgTYQEngLpSoXRfw+7Rnc+VcTjoIlOhmbul31TRlvAo57GToGJQT05ZnVG0prH3hqQWVvw==' WHERE MEMBER_ID = 'Griffy97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'XOFAmCPYGu9JSPuLn7jM0VrKIa4PWBitKN0gqNexk7zFvv5aZLWV+elL8mkppy1COJF6J2aPiOxSTQL1+r0kDA==' WHERE MEMBER_ID = 'Aguistin97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'RBinpNBQdlJJvOy4Li89YMa3j6x3NfaIsLUBgCFbJauFS85irCoB/CJUEZD4eqNFtopUdjWMsx23vpBbFvrtPg==' WHERE MEMBER_ID = 'Olin97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'JKXZ7OP5ZwZap/eikPW+O4juu5iuNUoxcQpLu2JBt+k4jv2chFU5X+sid8vf31yJBUT1AZEZ+ipfgwHnFwq2pg==' WHERE MEMBER_ID = 'Trey97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'evn3iHW7wxfND5zcNwbRIERsEcsJm7G7SDPoq+pzAmWw2UNB2Estlpveqw9DWGlmt0JfsqfKwEvMJbDPNcpFEw==' WHERE MEMBER_ID = 'Borg97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'u9g4UODFThgt8f1iknjboGxjsX/KKHh3qTiB1Iy+agqKpMHKcbXDcnK5qfSt9zuTotDqPcSbse7XysrHHaegPw==' WHERE MEMBER_ID = 'Bartlet97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '7vRemp0T9DDPZkhcDFMaLMokU5YzYKt6SLeIlh7bwKk+XuA3W0Xu3Zhm2k8apEdd6gyJQci6tXgrX/GhnSWIkQ==' WHERE MEMBER_ID = 'Renard97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'uB/SRcHMgumZSZ2s9h7SMnKQnvNW3OcHXHeSLDY9UGyvVLKJB5IogYg89kQ9h+9G14nTqgTnypq1ClzbMhdXPQ==' WHERE MEMBER_ID = 'Gordan97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'O1yGtLMcgo6EjazY1kA+iPmpqzcCINRcFN2m41YwPgKJhQIhJsEuvJ2hu9VLgxbJxIcIPTqev79T4ACAUECMbw==' WHERE MEMBER_ID = 'Georgy97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Ar6gjhNCOE93UQ/bYzOISnz1nvI4jGbbo6DQyCRaVv3ZXHbHPddSXHW7gn436K9rKRn1bqDcyhvQSG21cGi9gA==' WHERE MEMBER_ID = 'Emlyn97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'fPYHWkRvJKSpo0IzICCIfGFxZleTjXcoFWvpksPzLjymFkPnOZJyFTyZXxzm7JkG2XJWJcfd3a3GofFlQZStTQ==' WHERE MEMBER_ID = 'Moss97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'MpWhrybRx7Pf2ABa6tSgweXSDKIJwMVidbeRc9RaoFy2gRkB8KJl3O5c5joXV1j7w8TbC/ndrWlHYFF2uw/GAA==' WHERE MEMBER_ID = 'Morten97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 's/F47gZF7/F3wMynsByuFwHLapoOlyQt9B2yUDMEJ8tldd34MYQrcKI3WegenpawM39S0XXRaLPkn4g6TNbdWQ==' WHERE MEMBER_ID = 'Nikolaos97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '466m0IvzmZ1eHe/6JArkdCmrg0TFY7rIe/2Olb+dm6eAMIgIzCklQm5cFdPDjMV19bKujKuyn1J/6QuXTV7plQ==' WHERE MEMBER_ID = 'Berton97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'hMrhdd1NTBmstKlE8ukB8DnR88BXlODTCCwpfku2GoxuiAo9reA58WZyWAXZl0NgCyZwEBk0+js8CbIDlXe0LQ==' WHERE MEMBER_ID = 'Ingelbert97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'd3sEbohveFnsYJc6GovmKp6BLbsnFJ4UToQ8KdSKlES8E9SzxhJQL564zq1sDcgDVLw+GQvIxC1Xc2K0p5CnUQ==' WHERE MEMBER_ID = 'Anselm97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VGcoQyupoQxkXg13JBydAVNVAmG4joXzrhHPfqFdzbljAiuIpjKM4Nwl/J9c0t4sR2Qn35c4WNtjv/6Q2cTNag==' WHERE MEMBER_ID = 'Abelard97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'nEYrI9FQMT8PNnqSmONbelr6F35l59+iY1j0f+xkjp8/G33mYMwnPbf+6dOaVT6wtwJ83A8LY7G95CnVLkeszw==' WHERE MEMBER_ID = 'Edlin97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'IQ4cBsRvRpNzRld4eAX5c3nShHDXBYpBhGL2NQ9wnTB5HhcWLJXvkkiGSg2dFyso6NP3wJ07+2HCP/YjR8LtdA==' WHERE MEMBER_ID = 'Ernestus97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '9oNG+u/KsW2sdxS7OWcBKk7tpxSTGRqGM6SQpMrp0ZUXlgreJRPbPo70uKgFQrN1BwCFJ+0QF6jhJtOF9/NVDA==' WHERE MEMBER_ID = 'Reinhard97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'zh2LI19p1koM/EYLgonTAaZ2uHWpFIXwxITfr8tBhNY+4om0NadGcNKKmX3ceRQ9pfpqAPuNxikySwTg3CBFag==' WHERE MEMBER_ID = 'Aube97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'bDz5it8tUM3snd3hga/YfRKtTBEsJTZgtW0SfzVJyEaceKAKxHGvR+soU7D85bT+6N4+SkTtBfYNzd2mIAN9+w==' WHERE MEMBER_ID = 'Winston97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '4DU8nPo8AGhL7QBNxhyLSCd23YGO0yOlaK6PZb4mYiI5Lj7EWYutJnpH+gKt79INeZ9civey2u/xBfFC4Dekfw==' WHERE MEMBER_ID = 'Delaney97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'iqKphroBOeWTpFOH10Mb4iI2O7c0eVCwWnB1kGKJZ0g1n40JBmNke7wq7oSOewmZswukn+wd3P+NHnt99GmDIg==' WHERE MEMBER_ID = 'Ferrel97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'pjvO+fkBywOJwlmNWNjdQM1k6ziBoLdbnxLl4duZK/6ZeUG5L7diSGelQ/87vKSgW9r1u7PcQB7eVRM7679knQ==' WHERE MEMBER_ID = 'Caz97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'nJtzLvWKsrhTazfBTCBVEDYK3KLRkvhFY/pU9l4gjx3/vvBBf+6A3HRCQP62trFyLumYTLfFQylW8Dh8YkQOGQ==' WHERE MEMBER_ID = 'Salim97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Fv46G5NSJL9VUXlyU3v+m//VEXRZdqw+zIKpHu5mfP9tn9oPWIwqwF+/AF6WJYKRab8N0QkZBEWi19whxfdv5w==' WHERE MEMBER_ID = 'Jacques97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Cug47+jTyYOaX98vKaJeuCTXd8DP8UXRRN/gYQAXFzN30JPJkBg5WENZ9u/HOjH75UMgn0rbODXGbWlOq6WFUg==' WHERE MEMBER_ID = 'Armstrong97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'CcJx0l5SnTVNR5/1CjkYXFSZZeSXDvEi9lXeQlKWq8t+xwVmqLWyci1zYG73KP9sH2tTwvK4LJxJ//j1G/21vQ==' WHERE MEMBER_ID = 'Carlyle97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'MkEduUHCmvS8IgHNlVIRyUVPBApD53KPCKn5stBPqo3IGtDVF/M9rnqh4ZSJT2FSCWQBCq1t2ZNTWW6X3fMs1A==' WHERE MEMBER_ID = 'Hersh97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'OedmwmitunOIN2zY7nzV3CWeanatFrd7TLKY2HHioUHorZc8ocddePhJnLvfmBJVDA8F941qmiSv7XxjpifLGw==' WHERE MEMBER_ID = 'Nappie97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'REpeCEA0qjG+jVAE2h23a4w/EswvgRiLlzecvFGx5Rt429fmc7Mq3Q50a4SO9TKjbzDtRceWTHLFjzfJcQ7H2g==' WHERE MEMBER_ID = 'Lorrie97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '/WJxlXrcwmEC6hUwwY0Oh4GVrSieEnxvxk0VwJMZwjDn2j0Ny3mafm5qJNLQIMsreTwJBDBsJrI+LgUu0OUbtQ==' WHERE MEMBER_ID = 'Artemas97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kBBzqcBb+1YlDP5+Jp0F1WuAarITaG5dWn/gP4IgGKRHcNwag8/uIfgRPIab6EfE8tvIiJp1WFd3yh1Hb6vm5Q==' WHERE MEMBER_ID = 'Nev97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Xq/G314eQw5XgqmUXx8HI+KmURmyzhlEZfqA3lJ6NiaCkEDKHOmL58aSyhAwSQscx78knv/QdjR2rLL8ojHNwA==' WHERE MEMBER_ID = 'Nelson97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'XcMqsY9SzYfzN5yOSguGqpknGDP9f+h2Y+HuVNzAvoDyX6ZsQkQ7xU/YRTUbQ8hTr88hxGR+hJhIyZ7Dc5FwCA==' WHERE MEMBER_ID = 'Abraham97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'WJYUhVV8kxoIlw4JlN9AntdSRU/4F6mQC/SMpXlXxLAVF89pFaulxsh1uRN+U7dTTQF06sQo/3xi99r4nB/+EA==' WHERE MEMBER_ID = 'Gale97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'DcrWQdpHO0z0H90iBYnOpYjCJcCJEwIuvSW90Xl3wLauoeZftX0RVK80+Fk7B870aJYJBF6nBpi1M3rnMTXqbw==' WHERE MEMBER_ID = 'Ade97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kEKAtihlp4AjSoO6mtdO4fj0hCmWZefzpPnj6JGt8tFZpPdi/BClF/ndSSd8fTcIV40o0J0o5X4saJIwjT4Rew==' WHERE MEMBER_ID = 'Kerry97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Th67wQBHkegvY2FzR4kQThqhYBDtybMG6Inv8TDjejMgtCFYaXHtohCvauem3eP9Y1GqtRI3noP//sCH7tLIRA==' WHERE MEMBER_ID = 'Terry97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Ny4T+Ty/9FiZh983+YVpx7Vk34jUxVQclQsgzewG1EsFdZnoE+7R+tOpSCZRPF2X0NDAabeAJ11xux4ys/njXQ==' WHERE MEMBER_ID = 'Basile97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'xD8chWYtkTVw0LkjYDgrEYVZ5FFVtDmGmeId6DVNVLq4CV+x27PR0qgT2hmqZSK7NT8E7EyXjre7UhnpJ41kuQ==' WHERE MEMBER_ID = 'Harper97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'yqQEES5r+HA2ypdjefdfpx/zqv0FBo8SL6FgyUSfqSutpvSaGUlRGlPs+CJwfdz+O+wTXXIe6ybjVfYnBY78gA==' WHERE MEMBER_ID = 'Nico97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'yEPuX298nyUDZ8uunkIOBTzCvirM7Suq78XqLeYMMYp96ywa/+J9rEw+GQU/givFSjzGbrUt2Yi/1j7xUt57kg==' WHERE MEMBER_ID = 'Aldridge97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'KV70uyyvPeHWX3jSdIfbXsaTpkWXTgHNZ4IZgsp0d7wKuniVjFGCYa1Qn6k10VihOFdNxD/fSQfdXCKSz/8B7g==' WHERE MEMBER_ID = 'Jecho97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '83dgqq2EHKRghqFyP1/bFkrBut9Kh9ZW1dYYhRU5Z/xaPTV+txjWA7O8uWeEZk+Y2JfkGltYp9BsnDTURSqzsA==' WHERE MEMBER_ID = 'Sergeant97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'TeFp/2sJBi1t391aC52ulbZ2p13VhhvNa7jvcJaKZmvZJvrCWgMlcQFwXSvvLOzQrbe6HA5vGS4gDH29ARaAqg==' WHERE MEMBER_ID = 'Tore97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '+eFc6eSTQ5ZGs7th0idUL3Ts/9S0f26kUcYVTS7RsOEiUjJW13HtKyCNc/z2Y2Q44eJbWAbTb4b9GB3+ASpcqg==' WHERE MEMBER_ID = 'Brad97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Kxxa9goRnsB6qRW60APCtdtbteqid+imBwV9Snn70r66IHgm710uLwwz93rR/el8A/IHlglpHHRfKWi5WX5JPA==' WHERE MEMBER_ID = 'Brion97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '1BqDeixN78fOlCMgntzsgrycOIHnfyJxybANryi2dykFH1rjkspwF1DCvCEWNhKQ51lFfGDdUo9p4ZSHBt0sqg==' WHERE MEMBER_ID = 'Leeland97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'UcWUAsUCZyxB26HSe+T7hK638XoK2nri8B6qjlHJnz+7+QTEM8iuPh2/MkDqv89aRV1rwbZ0jE75GKSk1SJg7A==' WHERE MEMBER_ID = 'Uri97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Wb23vIbHcimLWNUctHGWzG36xPmyNWTLbONVut/glXzqC+Ph3EgaYHED7k21+s0s1gNSi47UEdiQ+X4BHL9Z1A==' WHERE MEMBER_ID = 'Christoper97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '7bo0Sjz6FegzLs1W5TyU9Q2Us+/ZQ5Yq1SoY72s15xP6m1Np47yKKWlJaDo7L/AwLzdl95SsYrV536cWm3Rnnw==' WHERE MEMBER_ID = 'Bartholomeo97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '29aOrWeVtJl6kXF/MLW/wmL3fHLzKyR/bgd3k8G+7ZtInWfUA9kxkqL4F1c1JQvEFSlwKSlWJRprTRVrnycqwQ==' WHERE MEMBER_ID = 'Frederic97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'QMm4fn+WzSMOShHMTJN3mUsJNgv9GvzKO5HLYkVz7vFtDTtRnzJzImRh3KyLsebGdXsy7WBwT3NQl/F8Z0OWeQ==' WHERE MEMBER_ID = 'Leupold97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kVaM/eqa27OkYMurL0/PK6/j3XyZy+71PGs+v197FDhvDkabj9N8DbIUSgKcI3uAEh1caYX6SovBt29w0B9vRw==' WHERE MEMBER_ID = 'Trumaine97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'GDa1N0AtmcUqvM50Hj8IkeygWOE6WLpzf+qAgPTxyd7L1H1smi3E/vdqQnhZfP1VQyT/r529jvbahjJ5czUAsw==' WHERE MEMBER_ID = 'Fran97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'Rfs/WBvwRXyfah6/JfrNQ3qPM8vBHk9ZmAHhT/pNR9ze16vVn44zRNqhJaXZSh6O1V0GJwjhwv06+F01CFOLiA==' WHERE MEMBER_ID = 'Daren97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '/X0tCYROM02JtPPL5sKUXrdAV4VWJPs+BjFMDrA8XhuG36V3ojDY80/kO7Q1JmJD1mfCn8iHp/jyozMcV+r1Ug==' WHERE MEMBER_ID = 'Walker97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'xyR5Lhl1c2em0PxV31WcLQbSag5NnC7QHhCz33kHSbMk/R/L22QI6razSjtm6oQYa6OfsMFfo8CchBADyucJNw==' WHERE MEMBER_ID = 'dsffsdf97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'lvMMAULzqjU+4ETVg5cCJpI9w/fgCHvchwHbCdEBQmrESM7qrtIRlugdu/GtDQrO7ktExhgDBD2KnjpcGqkVLA==' WHERE MEMBER_ID = 'Vlad97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '8qfQbykQ8g/xfjXapIR6+UVtQZhAy8O2tmqdvFKUYPpJuw7a7p9BpHcPIiMEqA3T/btyZnaQ1rP0tJjuP39cvw==' WHERE MEMBER_ID = 'Bogart97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '6yGhfGOWJDkRDSj/yl9qDEo3tn8uSbUnV1gvYY3te0rGt+5FGeiLTfK6qcXlRhRLoyV3YcRDc7uJ28loK5NDUg==' WHERE MEMBER_ID = 'Remus97362';
UPDATE MEMBER SET MEMBER_PASSWORD = '/M/WUvNoloeCnSGUiU+4reth2NC20lAEjnZ6vcaQVy20ajd4hAKync1jcN3rrcgLLhqBWgJRC8x4sUvFE6uexw==' WHERE MEMBER_ID = 'Benedict97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'sSynTjCMXozAeUZ3pR0ZXU/WiHM41476TRpvUKeO2h7+JjUfZSKXicBA1F7WF8XHhPoR3NeXCfKgs+ShAOlbtw==' WHERE MEMBER_ID = 'Carney97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'zVkqe2NWvq1FYrajxgdkB0kWShJCBwUIV1gL9fUkE88X6Ra6NdMmqVebVifS8AJ2Ai8jKvtJzjdKXxQwIK/ZQg==' WHERE MEMBER_ID = 'Fritz97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'YhH9O6xC/S+TH636BRYJ72IfG0AIn/9cbC32L+vJk+zDcIiW1BAKrJ4N3R/ycsurWsTeiKwnwmSeoffQmrvgfw==' WHERE MEMBER_ID = 'Zachary97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'WcIm3lscy72BMb8DLPscXMEYS10d5Trne/j456b6pj7tgfkDTcZPa1wLKoLhFDNrm93+f76RsfNFkOAEXPn6Rg==' WHERE MEMBER_ID = 'Denver97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VwC2Qxb0i1HzFiq4gLNJnr05W0JC6U3fbk6EVBIxRnn2nFp59hxCdf+LucNZkm+M9CtKuQMFkZpugscXSJsFgA==' WHERE MEMBER_ID = 'Julio97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'fjh+9r4jKAFDKH4pE32TXZYL6Zn9dzt6tSju2JuMTU6ts52Afza8kd+dxwrWqnii7L9rtNKtyfFuHp9HkSMTuA==' WHERE MEMBER_ID = 'Chickie97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'UFX9wINKN/j6tA9s/pOCoILjme9+rHF3F7FPAnR8Lq5kWQf0UZjVGcSCJo1mTBqKp8LZ5Wx95MkTY+MyVfIFTg==' WHERE MEMBER_ID = 'Lyn97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'JewbNhC7vUxl/TsUROietR2DcXSBioNDCLW6wgAyGiEtNID92fujR7aEAZ97bxGiTNFglI+kNruh2EdccV/kZg==' WHERE MEMBER_ID = 'Ulysses97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'KOCx15/ak0UcsqIjDecpase763tffSncGcx2N1kL1TAqfaDnPo8Zn7HKNWQh1A+9xZj7ZXsst9W81fO5+M5iqQ==' WHERE MEMBER_ID = 'Guthrey97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'mFMKObyi0J58TSZMYih4ie+qCYHgIl6J0nTLUCd3nASYj55JORXcnENB+piL4wCLaD2YQa/L7ZVgm0X+L4Igew==' WHERE MEMBER_ID = 'Erastus97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'zPoexqbGMLIoi13sFnX7rlJyai8BQ1fob2R4c1eqTBu5fS0hpRWIWqIvJJdgipvUDXntAh1ZrIPraoaUKM/kHg==' WHERE MEMBER_ID = 'Gauthier97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'wpva4AJUtwwkyQuvhrRmk6o9u+nq8RvDip8yDkk4C6YYbDLkpviiiwKABeuGJf67+1RzoxFv5i4eWehkkuGxng==' WHERE MEMBER_ID = 'Shell97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'HpQqQ+z9IPaVV7oByAw8ByDFlfsPchs+EbKyaMpbtNHMeZ251pPF5zD2fXWWQNRzRoA96uQNjQDM9is3P3MSCg==' WHERE MEMBER_ID = 'Gerome97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'USLOi8mc7c0LX6yg15icNY2MYvRQU86BatDE5piZhB4much/DI2WsS/oM8DGDIi6l8xh7VOIQbku4GrT54mTtg==' WHERE MEMBER_ID = 'Erl97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'xaqHnSJmMFEByV1RF+xmz4UtTR8ZdoXhzDTAnql3oQDKLB++QCMUOpY+zBipegUO+eoIx/us64VS4n4qOGPbaA==' WHERE MEMBER_ID = 'Land97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'C2zTs8rglelOmukC/HniN8KUEzVMRY9YgcmxkO/EqxsCENo648DTalTnqWVRyv0tEdxaIO+mA21RYxAYpJwmRQ==' WHERE MEMBER_ID = 'Antony97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'nG3PGmB/K5TtpG8VQadfyrouv3o6qYrisOuPOR4f+dIKX1Qjr5aoGtWjVLAfTfnfMcBawJjlVCxhkvedQ2Cr+A==' WHERE MEMBER_ID = 'Rowen97362';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kvOffyqGmDjNUIXm8X/IIQm8+YzWKkfLw3njjegLvAITojzubkoT3myq4K3Yo5AnLW8Ig8J0Mgsf9g28/G3XUA==' WHERE MEMBER_ID = 'admin1';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kvOffyqGmDjNUIXm8X/IIQm8+YzWKkfLw3njjegLvAITojzubkoT3myq4K3Yo5AnLW8Ig8J0Mgsf9g28/G3XUA==' WHERE MEMBER_ID = 'admin2';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kvOffyqGmDjNUIXm8X/IIQm8+YzWKkfLw3njjegLvAITojzubkoT3myq4K3Yo5AnLW8Ig8J0Mgsf9g28/G3XUA==' WHERE MEMBER_ID = 'admin3';
UPDATE MEMBER SET MEMBER_PASSWORD = 'kvOffyqGmDjNUIXm8X/IIQm8+YzWKkfLw3njjegLvAITojzubkoT3myq4K3Yo5AnLW8Ig8J0Mgsf9g28/G3XUA==' WHERE MEMBER_ID = 'admin4';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg==' WHERE MEMBER_ID = 'user1';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg==' WHERE MEMBER_ID = 'user2';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg==' WHERE MEMBER_ID = 'user3';
UPDATE MEMBER SET MEMBER_PASSWORD = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg==' WHERE MEMBER_ID = 'user4';

commit;

/////////// BOARD 테이블 ////////////////


  CREATE TABLE "DANAWABANG"."BOARD" 
   (	"BOARD_ID" NUMBER NOT NULL ENABLE, 
	"BOARD_TYPE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"BOARD_CATEGORY_ID" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"BOARD_TITLE" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"BOARD_CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"BOARD_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"BOARD_ENROLL_DATE" DATE NOT NULL ENABLE, 
	"BOARD_DELETE" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"IS_FIRST" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"BOARD_CATEGORY_NAME" VARCHAR2(1000 BYTE), 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MT_BOARD_1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "DANAWABANG"."MEMBER" ("MEMBER_ID") ENABLE, 
	 CONSTRAINT "FK_PI_BOARD_1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DANAWABANG"."PRODUCT" ("PRODUCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;



/////////// BOARD_ATTACHMENT 테이블 ////////////////


  CREATE TABLE "DANAWABANG"."BOARD_ATTACHMENT" 
   (	"BOARD_FILE_ID" NUMBER NOT NULL ENABLE, 
	"BOARD_FILE_LEVEL" NUMBER NOT NULL ENABLE, 
	"BOARD_ORIGIN_NAME" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"BOARD_CHANGE_NAME" VARCHAR2(2000 BYTE) NOT NULL ENABLE, 
	"BOARD_ID" NUMBER NOT NULL ENABLE, 
	"BOARD_FILE_PATH" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"BOARD_UPLOAD_DATE" DATE NOT NULL ENABLE, 
	"BOARD_FILE_DELETE" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARD_IMAGE" PRIMARY KEY ("BOARD_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BTB_IMAGE_1" FOREIGN KEY ("BOARD_ID")
	  REFERENCES "DANAWABANG"."BOARD" ("BOARD_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;



  CREATE TABLE "DANAWABANG"."CART" 
   (	"CART_ID" NUMBER NOT NULL ENABLE, 
	"CART_PRODUCT_AMOUNT" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CART_DELETE" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"CART_ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"PRODUCT_OPTION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_CART" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_MEMBER_TO_CART_1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "DANAWABANG"."MEMBER" ("MEMBER_ID") ENABLE, 
	 CONSTRAINT "FK_CP_CART_1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DANAWABANG"."PRODUCT" ("PRODUCT_ID") ENABLE, 
	 CONSTRAINT "FK_CPI_CART_1" FOREIGN KEY ("PRODUCT_OPTION_ID")
	  REFERENCES "DANAWABANG"."PRODUCT_OPTION" ("PRODUCT_OPTION_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "DANAWABANG"."MEMBER" 
   (	"MEMBER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"MEMBER_PASSWORD" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"MEMBER_EMAIL" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
	"MEMBER_PHONE" VARCHAR2(20 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(100 BYTE), 
	"IS_ADMIN" VARCHAR2(20 BYTE) DEFAULT 'USER' NOT NULL ENABLE, 
	"ADMIN_CODE" VARCHAR2(20 BYTE), 
	"MEMBER_DELETE" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_ENROLL_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "DANAWABANG"."ORDERS" 
   (	"ORDER_ID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ORDERER_NAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ORDERER_PHONE" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ORDERER_EMAIL" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ORDERER_ADDRESS" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"ORDERER_REQUEST" VARCHAR2(4000 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"ORDER_PRODUCT_NAME" VARCHAR2(4000 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER, 
	"ORDER_PRICE" NUMBER NOT NULL ENABLE, 
	"ORDER_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"IMP_UID" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ORDER" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_OPI_ORDERS_1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DANAWABANG"."PRODUCT" ("PRODUCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "DANAWABANG"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_AMOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PRODUCT_BRAND" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_PRICE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PRODUCT_DISCOUNT_RATE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"PRODUCT_DELIVERY_FEE" NUMBER DEFAULT 3000 NOT NULL ENABLE, 
	"PRODUCT_CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_TIP" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_ENROLL_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_STATUS" VARCHAR2(1000 BYTE) DEFAULT 'SALES' NOT NULL ENABLE, 
	"PRODUCT_DELETE" VARCHAR2(1000 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"PRODUCT_SIZE" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_PCI_BOARD_1" FOREIGN KEY ("PRODUCT_CATEGORY_ID")
	  REFERENCES "DANAWABANG"."PRODUCT_CATEGORY" ("PRODUCT_CATEGORY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "DANAWABANG"."PRODUCT_ATTACHMENT" 
   (	"PRODUCT_FILE_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FILE_LEVEL" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PRODUCT_ORIGIN_NAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_CHANGE_NAME" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_FILE_PATH" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_UPLOAD_DATE" DATE NOT NULL ENABLE, 
	"PRODUCT_FILE_DELETE" VARCHAR2(20 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRODUCTS_FILES" PRIMARY KEY ("PRODUCT_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_PI_PA_1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DANAWABANG"."PRODUCT" ("PRODUCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "DANAWABANG"."PRODUCT_CATEGORY" 
   (	"PRODUCT_CATEGORY_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_CATEGORY_NAME" VARCHAR2(1000 BYTE) DEFAULT '침대' NOT NULL ENABLE, 
	 CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("PRODUCT_CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DANAWABANG"."PRODUCT_CATEGORY"."PRODUCT_CATEGORY_NAME" IS '침대/매트리스/침구/커튼/조명/행거';


  CREATE TABLE "DANAWABANG"."PRODUCT_OPTION" 
   (	"PRODUCT_OPTION_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_OPTION_VALUE" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"PRODUCT_OPTION_ORIGIN_PRICE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PRODUCT_OPTION_STATUS" VARCHAR2(100 BYTE) DEFAULT 'SALES' NOT NULL ENABLE, 
	"PRODUCT_OPTION_DELETE" VARCHAR2(100 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_OPTION_AMOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_PRODUCT_OPTIONS" PRIMARY KEY ("PRODUCT_OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_PI_PO_1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "DANAWABANG"."PRODUCT" ("PRODUCT_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DANAWABANG"."PRODUCT_OPTION"."PRODUCT_OPTION_STATUS" IS 'SALES 판매중 SOLDOUT 품절';


  CREATE TABLE "DANAWABANG"."REPLY" 
   (	"REPLY_ID" NUMBER NOT NULL ENABLE, 
	"REPLY_CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"BOARD_ID" NUMBER NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ENROLL_DATE" DATE NOT NULL ENABLE, 
	"REPLY_DELETE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "REPLY_PK" PRIMARY KEY ("REPLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_BI_REPLY_1" FOREIGN KEY ("BOARD_ID")
	  REFERENCES "DANAWABANG"."BOARD" ("BOARD_ID") ENABLE, 
	 CONSTRAINT "FK_MI_REPLY_1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "DANAWABANG"."MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


////////////////////// 뷰 /////////////////////////////


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICCARTLIST" ("RNUM", "CART_ID", "CART_PRODUCT_AMOUNT", "PRODUCT_ID", "MEMBER_ID", "CART_DELETE", "CART_ENROLL_DATE", "PRODUCT_OPTION_ID") AS 
  select rownum RNUM, descboard."CART_ID",descboard."CART_PRODUCT_AMOUNT",descboard."PRODUCT_ID",descboard."MEMBER_ID",descboard."CART_DELETE",descboard."CART_ENROLL_DATE",descboard."PRODUCT_OPTION_ID"
      from(SELECT cart_id, cart_product_amount, product_id, member_id, cart_delete, cart_enroll_date, product_option_id FROM CART WHERE CART_DELETE = 'N' ORDER BY CART_ID DESC) DESCBOARD;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICFAQLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."BOARD_CATEGORY_NAME",descboard."MEMBER_ID"
      from (select board_id, board_type, BOARD_CATEGORY_ID, board_title, board_content, board_count, board_enroll_date,
            board_delete, is_first, BOARD_CATEGORY_NAME, member_id
              from board 
              where board_delete = 'N' AND BOARD_TYPE =1 AND BOARD_CATEGORY_ID BETWEEN 2451 AND 2455
              order by board_id desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICFAQLISTA" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."BOARD_CATEGORY_NAME",descboard."MEMBER_ID"
      from (select board_id, board_type, BOARD_CATEGORY_ID, board_title, board_content, board_count, board_enroll_date,
            board_delete, is_first, BOARD_CATEGORY_NAME, member_id
              from board 
              where board_delete = 'N' AND BOARD_TYPE =1 AND BOARD_CATEGORY_ID BETWEEN 2451 AND 2455
              order by board_COUNT desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICMAINLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "MEMBER_ID", "BOARD_CATEGORY_NAME") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."MEMBER_ID",descboard."BOARD_CATEGORY_NAME"
      from (select BOARD_ID, BOARD_TYPE, BOARD_CATEGORY_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, BOARD_ENROLL_DATE,
            BOARD_DELETE, IS_FIRST, MEMBER_ID, BOARD_CATEGORY_NAME
              from board 
              where board_delete = 'N' AND (BOARD_CATEGORY_ID BETWEEN 2421 AND 2425 OR BOARD_CATEGORY_ID = 2430)
              order by BOARD_ENROLL_DATE desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICMLIST" ("RNUM", "MEMBER_NAME", "MEMBER_ID", "MEMBER_PASSWORD", "MEMBER_EMAIL", "MEMBER_PHONE", "MEMBER_ADDRESS", "IS_ADMIN", "ADMIN_CODE", "MEMBER_DELETE", "MEMBER_ENROLL_DATE") AS 
  SELECT ROWNUM RNUM, DESCBOARD."MEMBER_NAME",DESCBOARD."MEMBER_ID",DESCBOARD."MEMBER_PASSWORD",DESCBOARD."MEMBER_EMAIL",DESCBOARD."MEMBER_PHONE",DESCBOARD."MEMBER_ADDRESS",DESCBOARD."IS_ADMIN",DESCBOARD."ADMIN_CODE",DESCBOARD."MEMBER_DELETE",DESCBOARD."MEMBER_ENROLL_DATE" 
       FROM(SELECT *
         FROM MEMBER
         WHERE MEMBER_DELETE = 'N' 
         ORDER BY MEMBER_ENROLL_DATE DESC) DESCBOARD;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICNDETAIL" ("BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "MEMBER_ID", "BOARD_CATEGORY_NAME") AS 
  select BOARD_ID, BOARD_TYPE, BOARD_CATEGORY_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, BOARD_ENROLL_DATE,
            BOARD_DELETE, IS_FIRST, MEMBER_ID, BOARD_CATEGORY_NAME
              from board 
              where board_delete = 'N' AND BOARD_CATEGORY_ID = 2440;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICNLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "MEMBER_ID", "BOARD_CATEGORY_NAME") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."MEMBER_ID",descboard."BOARD_CATEGORY_NAME"
      from (select BOARD_ID, BOARD_TYPE, BOARD_CATEGORY_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, BOARD_ENROLL_DATE,
            BOARD_DELETE, IS_FIRST, MEMBER_ID, BOARD_CATEGORY_NAME
              from board 
              where board_delete = 'N' AND BOARD_CATEGORY_ID = 2440
              order by is_first desc, board_id desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICOTOLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  SELECT
        ROWNUM rnum,
        descboard."BOARD_ID",
        descboard."BOARD_TYPE",
        descboard."BOARD_CATEGORY_ID",
        descboard."BOARD_TITLE",
        descboard."BOARD_CONTENT",
        descboard."BOARD_COUNT",
        descboard."BOARD_ENROLL_DATE",
        descboard."BOARD_DELETE",
        descboard."IS_FIRST",
        descboard."BOARD_CATEGORY_NAME",
        descboard."MEMBER_ID"
    FROM
        (
            SELECT
                board_id,
                board_type,
                board_category_id,
                board_title,
                board_content,
                board_count,
                board_enroll_date,
                board_delete,
                is_first,
                board_category_name,
                member_id
            FROM
                board
            WHERE
                    board_delete = 'N'
                AND board_type = 2
                AND board_category_id = 2460
            ORDER BY
                board_id DESC
        ) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICPLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."BOARD_CATEGORY_NAME",descboard."MEMBER_ID"
      from (select board_id, board_type, BOARD_CATEGORY_ID, board_title, board_content, board_count, board_enroll_date,
            board_delete, is_first, BOARD_CATEGORY_NAME, MEMBER_ID
              from board
              where board_delete = 'N' AND BOARD_TYPE =2 AND BOARD_CATEGORY_ID = 2430
              order by board_id desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICPRODUCTLIST" ("RNUM", "PRODUCT_ID", "PRODUCT_NAME", "PRODUCT_CATEGORY_ID", "PRODUCT_AMOUNT", "PRODUCT_BRAND", "PRODUCT_PRICE", "PRODUCT_DISCOUNT_RATE", "PRODUCT_DELIVERY_FEE", "PRODUCT_CONTENT", "PRODUCT_TIP", "PRODUCT_ENROLL_DATE", "PRODUCT_STATUS", "PRODUCT_DELETE", "PRODUCT_SIZE") AS 
  select rownum rnum, descboard."PRODUCT_ID",descboard."PRODUCT_NAME",descboard."PRODUCT_CATEGORY_ID",descboard."PRODUCT_AMOUNT",descboard."PRODUCT_BRAND",descboard."PRODUCT_PRICE",descboard."PRODUCT_DISCOUNT_RATE",descboard."PRODUCT_DELIVERY_FEE",descboard."PRODUCT_CONTENT",descboard."PRODUCT_TIP",descboard."PRODUCT_ENROLL_DATE",descboard."PRODUCT_STATUS",descboard."PRODUCT_DELETE",descboard."PRODUCT_SIZE"
      from (select PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY_ID, PRODUCT_AMOUNT, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_DISCOUNT_RATE,
      PRODUCT_DELIVERY_FEE, PRODUCT_CONTENT, PRODUCT_TIP, PRODUCT_ENROLL_DATE, PRODUCT_STATUS, PRODUCT_DELETE, PRODUCT_SIZE
      from product
      where product_delete = 'N' order by product_id desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICRLIST" ("RNUM", "REPLY_ID", "REPLY_CONTENT", "BOARD_ID", "MEMBER_ID", "ENROLL_DATE", "REPLY_DELETE", "BOARD_CATEGORY_NAME") AS 
  SELECT "RNUM","REPLY_ID","REPLY_CONTENT","BOARD_ID","MEMBER_ID","ENROLL_DATE","REPLY_DELETE","BOARD_CATEGORY_NAME" FROM(
SELECT ROWNUM RNUM, DESCBOARD.* FROM
(SELECT REPLY_ID, REPLY.REPLY_CONTENT, BOARD_ID, REPLY.MEMBER_ID, REPLY.ENROLL_DATE, REPLY.REPLY_DELETE, BOARD.BOARD_CATEGORY_NAME FROM REPLY JOIN BOARD USING(BOARD_ID) WHERE REPLY_DELETE = 'N'
order by reply_id desc) DESCBOARD);


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICOTOLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  SELECT
        ROWNUM rnum,
        descboard."BOARD_ID",
        descboard."BOARD_TYPE",
        descboard."BOARD_CATEGORY_ID",
        descboard."BOARD_TITLE",
        descboard."BOARD_CONTENT",
        descboard."BOARD_COUNT",
        descboard."BOARD_ENROLL_DATE",
        descboard."BOARD_DELETE",
        descboard."IS_FIRST",
        descboard."BOARD_CATEGORY_NAME",
        descboard."MEMBER_ID"
    FROM
        (
            SELECT
                board_id,
                board_type,
                board_category_id,
                board_title,
                board_content,
                board_count,
                board_enroll_date,
                board_delete,
                is_first,
                board_category_name,
                member_id
            FROM
                board
            WHERE
                    board_delete = 'N'
                AND board_type = 2
                AND board_category_id = 2460
            ORDER BY
                board_id DESC
        ) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICPLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "BOARD_CATEGORY_NAME", "MEMBER_ID") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."BOARD_CATEGORY_NAME",descboard."MEMBER_ID"
      from (select board_id, board_type, BOARD_CATEGORY_ID, board_title, board_content, board_count, board_enroll_date,
            board_delete, is_first, BOARD_CATEGORY_NAME, MEMBER_ID
              from board
              where board_delete = 'N' AND BOARD_TYPE =2 AND BOARD_CATEGORY_ID = 2430
              order by board_id desc) descboard;



  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICPRODUCTLIST" ("RNUM", "PRODUCT_ID", "PRODUCT_NAME", "PRODUCT_CATEGORY_ID", "PRODUCT_AMOUNT", "PRODUCT_BRAND", "PRODUCT_PRICE", "PRODUCT_DISCOUNT_RATE", "PRODUCT_DELIVERY_FEE", "PRODUCT_CONTENT", "PRODUCT_TIP", "PRODUCT_ENROLL_DATE", "PRODUCT_STATUS", "PRODUCT_DELETE", "PRODUCT_SIZE") AS 
  select rownum rnum, descboard."PRODUCT_ID",descboard."PRODUCT_NAME",descboard."PRODUCT_CATEGORY_ID",descboard."PRODUCT_AMOUNT",descboard."PRODUCT_BRAND",descboard."PRODUCT_PRICE",descboard."PRODUCT_DISCOUNT_RATE",descboard."PRODUCT_DELIVERY_FEE",descboard."PRODUCT_CONTENT",descboard."PRODUCT_TIP",descboard."PRODUCT_ENROLL_DATE",descboard."PRODUCT_STATUS",descboard."PRODUCT_DELETE",descboard."PRODUCT_SIZE"
      from (select PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY_ID, PRODUCT_AMOUNT, PRODUCT_BRAND, PRODUCT_PRICE, PRODUCT_DISCOUNT_RATE,
      PRODUCT_DELIVERY_FEE, PRODUCT_CONTENT, PRODUCT_TIP, PRODUCT_ENROLL_DATE, PRODUCT_STATUS, PRODUCT_DELETE, PRODUCT_SIZE
      from product
      where product_delete = 'N' order by product_id desc) descboard;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICRLIST" ("RNUM", "REPLY_ID", "REPLY_CONTENT", "BOARD_ID", "MEMBER_ID", "ENROLL_DATE", "REPLY_DELETE", "BOARD_CATEGORY_NAME") AS 
  SELECT "RNUM","REPLY_ID","REPLY_CONTENT","BOARD_ID","MEMBER_ID","ENROLL_DATE","REPLY_DELETE","BOARD_CATEGORY_NAME" FROM(
SELECT ROWNUM RNUM, DESCBOARD.* FROM
(SELECT REPLY_ID, REPLY.REPLY_CONTENT, BOARD_ID, REPLY.MEMBER_ID, REPLY.ENROLL_DATE, REPLY.REPLY_DELETE, BOARD.BOARD_CATEGORY_NAME FROM REPLY JOIN BOARD USING(BOARD_ID) WHERE REPLY_DELETE = 'N'
order by reply_id desc) DESCBOARD);


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICSDETAIL" ("BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "MEMBER_ID", "BOARD_CATEGORY_NAME") AS 
  select BOARD_ID, BOARD_TYPE, BOARD_CATEGORY_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, BOARD_ENROLL_DATE,
            BOARD_DELETE, IS_FIRST, MEMBER_ID, BOARD_CATEGORY_NAME
              from board 
              where board_delete = 'N' AND BOARD_CATEGORY_ID BETWEEN 2421 AND 2425;


  CREATE OR REPLACE FORCE VIEW "DANAWABANG"."BASICSLIST" ("RNUM", "BOARD_ID", "BOARD_TYPE", "BOARD_CATEGORY_ID", "BOARD_TITLE", "BOARD_CONTENT", "BOARD_COUNT", "BOARD_ENROLL_DATE", "BOARD_DELETE", "IS_FIRST", "MEMBER_ID", "BOARD_CATEGORY_NAME") AS 
  select rownum rnum, descboard."BOARD_ID",descboard."BOARD_TYPE",descboard."BOARD_CATEGORY_ID",descboard."BOARD_TITLE",descboard."BOARD_CONTENT",descboard."BOARD_COUNT",descboard."BOARD_ENROLL_DATE",descboard."BOARD_DELETE",descboard."IS_FIRST",descboard."MEMBER_ID",descboard."BOARD_CATEGORY_NAME"
      from (select BOARD_ID, BOARD_TYPE, BOARD_CATEGORY_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, BOARD_ENROLL_DATE,
            BOARD_DELETE, IS_FIRST, MEMBER_ID, BOARD_CATEGORY_NAME
              from board 
              where board_delete = 'N' AND BOARD_CATEGORY_ID BETWEEN 2421 AND 2425
              order by is_first desc, board_id desc) descboard;

/////////////////// 시퀀스 //////////////////

   CREATE SEQUENCE  "DANAWABANG"."SEQ_BID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 269 NOCACHE  NOORDER  NOCYCLE ;



   CREATE SEQUENCE  "DANAWABANG"."SEQ_CID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;


   CREATE SEQUENCE  "DANAWABANG"."SEQ_FID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 176 NOCACHE  NOORDER  NOCYCLE ;


   CREATE SEQUENCE  "DANAWABANG"."SEQ_PAID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 385 NOCACHE  NOORDER  NOCYCLE ;


   CREATE SEQUENCE  "DANAWABANG"."SEQ_PID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 93 NOCACHE  NOORDER  NOCYCLE ;


   CREATE SEQUENCE  "DANAWABANG"."SEQ_POID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 251 CACHE 20 NOORDER  NOCYCLE ;


   CREATE SEQUENCE  "DANAWABANG"."SEQ_RID"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 106 NOCACHE  NOORDER  NOCYCLE ;

