/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-06 03:37:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/member/../common/bottom.jsp", Long.valueOf(1625409665998L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/top.jsp", Long.valueOf(1625462718320L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/navbar.jsp", Long.valueOf(1625462715336L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap-4.3.1.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap-4.3.1.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* 입력란 길이 */\r\n");
      out.write(".form-control {\r\n");
      out.write("	width: 290px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 필수항목의 (필수) */\r\n");
      out.write(".need {\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("	color: rgb(17, 187, 255);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	<div id=\"main-container\" class=\"container\">\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member) session.getAttribute("loginUser"); 
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>다나와방</title>\r\n");
      out.write("<!-- --------------------- -->\r\n");
      out.write("<style>\r\n");
      out.write("/*상단 관련 스타일*/\r\n");
      out.write("/*검색창*/\r\n");
      out.write(".btn-outline-secondary {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:hover {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #FBA481;\r\n");
      out.write("	border-color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:focus, .btn-outline-secondary.focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active, .show>.btn-outline-secondary.dropdown-toggle\r\n");
      out.write("	{\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active:focus,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active:focus,\r\n");
      out.write("	.show>.btn-outline-secondary.dropdown-toggle:focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("/*아이콘 색변경*/\r\n");
      out.write(".i-plain {\r\n");
      out.write("	color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".i-plain:hover {\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("/*메뉴버튼*/\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 100%;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   display: none;\r\n");
      out.write("   float: left;\r\n");
      out.write("   min-width: 250px;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   background-color: #fff;\r\n");
      out.write("   background-clip: padding-box;\r\n");
      out.write("   border: 2px solid rgba(17, 187, 255, 1);\r\n");
      out.write("   border-radius: 0.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("   color: #11bbff;\r\n");
      out.write("}\r\n");
      out.write(".button1{\r\n");
      out.write("	border: 1px solid rgb(17, 187, 255);\r\n");
      out.write("	background-color: rgb(17, 187, 255);\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ----------------아이콘 호버시 색 바꾸기------------------- */\r\n");
      out.write(".i-side {\r\n");
      out.write("     color: #fff;\r\n");
      out.write(" }\r\n");
      out.write(".i-side:hover {\r\n");
      out.write("     color: #FBA481;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(".side-nav {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".side-nav:hover{\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("	text-decoration:none !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	<form action=\"");
      out.print( request.getContextPath() );
      out.write("/searchAll.bo\" id=\"searchAll\" method=\"post\" onsubmit=\"return search();\">\r\n");
      out.write("		<!-- 1행 -->\r\n");
      out.write("		<div class=\"row\" id=\"top-bar\">\r\n");
      out.write("			<!-- 상단 광고 -->\r\n");
      out.write("			<div class=\"col-12\" onclick=\"location.href='");
      out.print( request.getContextPath());
      out.write("/boardPromotionDetail.bo?bId=271'\"\r\n");
      out.write("				style=\"background: #11BBFF; text-align: center; cursor: pointer; line-height: 30px; font-size: 14px; font-weight: bold; color: white;\">\r\n");
      out.write("				정리정돈의 달인이 될 수 있는 기회, 수납/정리 프로모션으로 함께 떠나요!</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 2행 -->\r\n");
      out.write("		<div class=\"row\" id=\"secondRow\">\r\n");
      out.write("			<!-- 로고  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<div id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/mainPage.me';\"\r\n");
      out.write("					style=\"color: #11BBFF; font-size: 32px; text-align: center; vertical-align: middle; margin-top: 16px; font-weight: bold; cursor: pointer; color: #11BBFF;\">\r\n");
      out.write("					<i class=\"bi bi-house\" style=\"font-size: 37px;\"></i>다나와방\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 검색창  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<!-- 검색 아이콘  -->\r\n");
      out.write("				<div style=\"margin-top: 30px;\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력해주세요\" id=\"searchAllWord\" name=\"searchAllWord\"\r\n");
      out.write("						style=\"font-size: 14px; border:2px solid #11bbff; margin-left: 30px;\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<button class=\"btn btn-outline-secondary\" type=\"submit\"\r\n");
      out.write("					id=\"main-search\" style=\"font-size: 14px; margin-top: 30px;\">검색</button>\r\n");
      out.write("					\r\n");
      out.write("			</div>\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("			<!-- 로그인/회원가입 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"login\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그인/회원가입</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("			<!-- 로그아웃 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"logout\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그아웃</div>\r\n");
      out.write("			</div>	\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			<!-- 마이페이지 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 42px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("ADMIN")) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/adminMember.me';\"></i>\r\n");
      out.write("			");
 } else {
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myOrder.bo';\"></i>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 고객센터 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 20px; cursor: pointer; font-size: 37px;\">\r\n");
      out.write("				<i class=\"bi bi-headset i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 장바구니 아이콘 -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 38px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("USER")) { 
      out.write("\r\n");
      out.write("            <i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/cart.bo';\"></i>\r\n");
      out.write("         	");
 } 
      out.write("   	\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("		<!-- 3행 -->\r\n");
      out.write("		<!-- 메뉴아이콘 -->\r\n");
      out.write("		<div class=\"row\" id=\"thirdRow\"\r\n");
      out.write("			style=\"text-align: center; margin-top: 15px;\">\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<div class=\"dropdown\" style=\"margin-top: -10px;\">\r\n");
      out.write("					<a class=\"btn-group-vertical\" href=\"#\" role=\"button\"\r\n");
      out.write("						id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"bi bi-list i-plain\"\r\n");
      out.write("						style=\"font-size: 35px;\"></i></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\"\r\n");
      out.write("						style=\"text-align: center; font-weight: bold;\">\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">6평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardStore.bo?currentPage=1&checkedRoomSize=6\"><img\r\n");
      out.write("								src=\"images/6평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">8평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardStore.bo?currentPage=1&checkedRoomSize=8\"><img\r\n");
      out.write("								src=\"images/8평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">10평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardStore.bo?currentPage=1&checkedRoomSize=10\"><img\r\n");
      out.write("								src=\"images/10평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">12평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardStore.bo?currentPage=1&checkedRoomSize=12\"><img\r\n");
      out.write("								src=\"images/12평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">14평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"");
      out.print(request.getContextPath() );
      out.write("/boardStore.bo?currentPage=1&checkedRoomSize=14\"><img\r\n");
      out.write("								src=\"images/14평.png\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 스토어 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardStore.bo';\"\r\n");
      out.write("				style=\"font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">스토어</div>\r\n");
      out.write("			<!-- 셀프가이드 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardSelfGuide.bo';\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">셀프가이드</div>\r\n");
      out.write("			<!-- 프로모션 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardPromotion.bo'\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">프로모션</div>\r\n");
      out.write("			<div class=\"col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 구분선 -->\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"margin-top: 20px; width: 100%; border-bottom: 2px solid #11BBFF; margin-bottom: 15px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 15px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- ------------------------스크립트 공간 ----------------------- -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- 상단 스크립트 -->\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#top-bar').children().hover(function() {\r\n");
      out.write("			$(this).css({'background-color' : '#FBA481'});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({'background-color' : '#11BBFF'});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로고\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#logo').hover(function() {\r\n");
      out.write("			$(this).css({'font-size' : '34px', 'color' : '#FBA481'});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({'font-size' : '32px', 'color' : '#11bbff'});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로그인\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#login').hover(function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#FBA481',\r\n");
      out.write("				'border-color' : '#FBA481'\r\n");
      out.write("			});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#11BBFF',\r\n");
      out.write("				'border-color' : '#11BBFF'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로그아웃\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#logout').hover(function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#FBA481',\r\n");
      out.write("				'border-color' : '#FBA481'\r\n");
      out.write("			});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#11BBFF',\r\n");
      out.write("				'border-color' : '#11BBFF'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//3행\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#thirdRow').children().hover(function() {\r\n");
      out.write("			$(this).css('color', '#FBA481');\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css('color', '#11BBFF');\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 검색창 \r\n");
      out.write("	function search() {\r\n");
      out.write("		var keyword = document.getElementById('searchAllWord').value;\r\n");
      out.write("		\r\n");
      out.write("		console.log(keyword);\r\n");
      out.write("		if (keyword == '' || keyword.length == 0) {\r\n");
      out.write("			document.getElementById('searchAllWord').focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<!-- 필요한 외부 script -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 40px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col\"\r\n");
      out.write("				style=\"text-align: center; font-size: 30px; font-weight: bold; color: rgb(17, 187, 255);\">\r\n");
      out.write("				회원가입</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 20px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\"\r\n");
      out.write("			style=\"line-height: 40px; font-weight: bold; font-size: 17px;\">\r\n");
      out.write("			<div class=\"col\"></div>\r\n");
      out.write("			<div class=\"col-6\">\r\n");
      out.write("				<form action=\"");
      out.print( request.getContextPath() );
      out.write("/insert.me\" name=\"signUpForm\" onsubmit=\"return enroll();\">\r\n");
      out.write("					이름<br> \r\n");
      out.write("					<input type=\"text\" id=\"name\" name=\"name\" class=\"form-control\" placeholder=\"이름\">\r\n");
      out.write("					아이디<br>\r\n");
      out.write("					<input type=\"text\" id=\"id\" name=\"id\" class=\"form-control\" placeholder=\"중복확인 버튼을 눌러주세요\" style=\"display: inline; background: white;\" readonly>\r\n");
      out.write("					<button type=\"button\" class=\"button1\" style=\"margin-left: 20px;\" onclick=\"idCheck();\">중복확인</button><br>\r\n");
      out.write("					비밀번호<br> \r\n");
      out.write("					<span style=\"font-weight: normal; font-size: 12px;\">8~15자리이하 영,숫자를 입력해주세요</span><br>\r\n");
      out.write("					<input type=\"password\" id=\"pw1\"	class=\"form-control\" placeholder=\"비밀번호\"> 비밀번호 확인<br>\r\n");
      out.write("					<input type=\"password\" id=\"pw2\" name=\"pwd\" class=\"form-control\" placeholder=\"비밀번호 확인\" style=\"display: inline\" onblur=\"checkPw();\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 비밀번호 동일한지 알림 -->\r\n");
      out.write("					<span id=\"check\" style=\"font-size: 15px; font-weight: normal;\">&nbsp;</span><br>\r\n");
      out.write("\r\n");
      out.write("					이메일<br><input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\"placeholder=\"이메일\" style=\"display: inline; background: white;\" >\r\n");
      out.write("					<button type=\"button\" class=\"button1\" style=\"margin-left: 20px;\" onclick=\"emailCheck();\">인증하기</button><br>\r\n");
      out.write("					\r\n");
      out.write("					전화번호<br><input type=\"text\" id=\"phone\" name=\"phone\" class=\"form-control\" placeholder=\"핸드폰 번호 : 000-0000-0000\">\r\n");
      out.write("					\r\n");
      out.write("					주소<br>\r\n");
      out.write("					<input type=\"text\" id=\"post\" name=\"post\" class=\"form-control\" style=\"width: 150px;\"placeholder=\"우편번호 : 00000\">\r\n");
      out.write("					<input type=\"text\" id=\"add1\" name=\"add1\" class=\"form-control\" style=\"margin-top: 5px;\" placeholder=\"주소\">\r\n");
      out.write("					<input type=\"text\" id=\"add2\" name=\"add2\" class=\"form-control\" style=\"margin-top: 5px;\" placeholder=\"상세주소\">\r\n");
      out.write("\r\n");
      out.write("					<!-- 약관동의  -->\r\n");
      out.write("					약관동의<br>\r\n");
      out.write("					<div style=\"border: 1px solid black; width: 460px; height: 230px;\">\r\n");
      out.write("						<table\r\n");
      out.write("							style=\"margin-left: 20px; line-height: 40px; width: 410px; font-size: 16px; font-weight: normal;\">\r\n");
      out.write("							<tr style=\"border-bottom: 1px solid black;\">\r\n");
      out.write("								<th style=\"width: 30px;\"><input type=\"checkbox\" id=\"all\"\r\n");
      out.write("									name=\"agree\" onclick=\"selectAll();\"></th>\r\n");
      out.write("								<th>전체동의</th>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><input type=\"checkbox\" name=\"agree\"	onclick=\"selectOne();\"></td>\r\n");
      out.write("								<td>만 14세 이상입니다.<span class=\"need\">&nbsp;(필수)</span></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><input type=\"checkbox\" name=\"agree\"	onclick=\"selectOne();\"></td>\r\n");
      out.write("								<td>이용약관<span class=\"need\">&nbsp;(필수)</span></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><input type=\"checkbox\" name=\"agree\"	onclick=\"selectOne();\"></td>\r\n");
      out.write("								<td>개인정보수집 및 이용동의<span class=\"need\">&nbsp;(필수)</span></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><input type=\"checkbox\" name=\"agree\"	onclick=\"selectOne();\"></td>\r\n");
      out.write("								<td>이벤트,프로모션 알림 메일 및 SMS 수신<span\r\n");
      out.write("									style=\"font-size: 15px; color: gray;\">&nbsp;(선택)</span></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<br>\r\n");
      out.write("					<!-- 회원가입 완료 버튼 -->\r\n");
      out.write("					<button type=\"submit\" class=\"button1\"\r\n");
      out.write("						style=\"margin-left: 30px; width: 400px; height: 45px; text-align: center; font-size: 22px;\">\r\n");
      out.write("						회원가입</button>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div style=\"margin-bottom: 120px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>다나와방</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 40px;\">\r\n");
      out.write("			<div class=\"col-1\"></div>\r\n");
      out.write("			<div class=\"col-4\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\"\r\n");
      out.write("				style=\"color: black; font-size: 22px; font-weight: bold; cursor: pointer; line-height:20px; margin-left: 20px; margin-bottom:-10px;\">\r\n");
      out.write("				고객센터 : 1555-5551<br><span style=\"font-size: 13px; font-weight: normal; color:black;\">평일 09:00 ~ 18:00 (주말 & 공휴일 제외)</span></div>\r\n");
      out.write("			<div class=\"col-6\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 20px; color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-right:-20px;\"></div>\r\n");
      out.write("			<div class=\"col-6\">\r\n");
      out.write("			<div class=\"row\" style=\"margin:auto; text-align: center;\">\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/introduction.me';\">회사소개</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/accessTerms.me';\">이용약관</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/privacyPolicy.me';\">개인정보처리방침</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardNotice.bo';\">공지사항</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 10px; margin-left: 10px; font-size: 12px;\">\r\n");
      out.write("			<div class=\"col-1\"></div>\r\n");
      out.write("			<div class=\"col-11\">\r\n");
      out.write("				<p>\r\n");
      out.write("					상호명 : (주)다나와방 / 이메일 : danawabang@danawabang.com / 대표이사 : 박신우 /\r\n");
      out.write("					사업자등록번호 : 999-88-77777 / 통신판매업신고번호 : 제2021-서울역삼-0215호<br> 주소 :\r\n");
      out.write("					서울 역삼구 역삼대로56길 6 타워팰리스타워 31층 <br> Copyright 2021. danawabang,\r\n");
      out.write("					Co., Ltd. All rights reserved\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>다나와방</title>\r\n");
      out.write("<style>\r\n");
      out.write("	/* ----------스크롤시 하단아이콘  보이기 --------------------------------------------------------------------- */\r\n");
      out.write(".bottomNav {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	font-size: 50px;\r\n");
      out.write("	color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottomNav {\r\n");
      out.write("	bottom: -90px;\r\n");
      out.write("	transition: bottom .2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottomNav.show {\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* ------------따라다니는 오른쪽 네비게이션---------------------------------------------------------- */\r\n");
      out.write("#followquick {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 200px;\r\n");
      out.write("	right: 50%;\r\n");
      out.write("	margin-top: 270px;\r\n");
      out.write("	margin-right: -800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 오른쪽 따라 다니는 네비게이션 바 -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div id=\"followquick\" style=\"width: 7%;\">\r\n");
      out.write("		<div class=\"row\"\r\n");
      out.write("			style=\"height: 200px; background: #11BBFF; color: #fff; border-radius: 10px;\">\r\n");
      out.write("			<div class=\"col\"\r\n");
      out.write("				style=\"margin-top: -10px; text-align: center; cursor: pointer;\"\r\n");
      out.write("				onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<div class=\"side-nav\"\r\n");
      out.write("						style=\"font-size: 19px; font-weight: bold; margin-top: 15px;\">\r\n");
      out.write("						<i class=\"bi bi-house\" style=\"font-size: 45px; color: #fff\"></i><br>\r\n");
      out.write("						<div style=\"color: #fff;\">\r\n");
      out.write("							다나와방<br>고객센터\r\n");
      out.write("						</div>\r\n");
      out.write("						<br>\r\n");
      out.write("						<div\r\n");
      out.write("							style=\"font-size: 23px; font-weight: bold; color: #fff; margin-top: -10px;\">1555-5551</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"margin-top: 5px; width: 100%; border-bottom: 2px solid #fff\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 탭 하면 맨위로 올라가는 버튼 -->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-10\"></div>\r\n");
      out.write("		<div class=\"col-1\" style=\"\">\r\n");
      out.write("			<i class=\"bi bi-arrow-up-circle-fill bottomNav i-plain\"\r\n");
      out.write("				style=\"cursor: pointer;\" onclick=\"window.scrollTo(0,0);\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>	\r\n");
      out.write("	<!-- 스크롤 시 하단 아이콘 보이기-------------------------------------------- -->\r\n");
      out.write("	<script>\r\n");
      out.write("	//Javascript\r\n");
      out.write("	var lastScrollTop = 0;\r\n");
      out.write("	var delta = 10;\r\n");
      out.write("	var fixBox = document.querySelector('.bottomNav');\r\n");
      out.write("	var fixBoxHeight = fixBox.offsetHeight;\r\n");
      out.write("	var didScroll;\r\n");
      out.write("	//스크롤 이벤트 \r\n");
      out.write("	window.onscroll = function(e) {\r\n");
      out.write("	    didScroll = true;\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	//0.25초마다 스크롤 여부 체크하여 스크롤 중이면 hasScrolled() 호출\r\n");
      out.write("	setInterval(function(){\r\n");
      out.write("	    if(didScroll){\r\n");
      out.write("	        hasScrolled();\r\n");
      out.write("	        didScroll = false;\r\n");
      out.write("	    }\r\n");
      out.write("	}, 250);\r\n");
      out.write("\r\n");
      out.write("	function hasScrolled(){\r\n");
      out.write("	    var nowScrollTop = window.scrollY;\r\n");
      out.write("	    if(Math.abs(lastScrollTop - nowScrollTop) <= delta){\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(nowScrollTop > lastScrollTop && nowScrollTop > fixBoxHeight){\r\n");
      out.write("	        //Scroll down\r\n");
      out.write("	        fixBox.classList.add('show');\r\n");
      out.write("	    }else{\r\n");
      out.write("	        if(nowScrollTop + window.innerHeight < document.body.offsetHeight){\r\n");
      out.write("	            //Scroll up\r\n");
      out.write("	            fixBox.classList.remove('show');\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	    lastScrollTop = nowScrollTop;\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- --------------------따라오는 오른쪽 네비게이션 ------------------------------- !-->\r\n");
      out.write("\r\n");
      out.write("	//follow quick menu\r\n");
      out.write("	$(window).scroll(function(){\r\n");
      out.write("	var scrollTop = $(document).scrollTop();\r\n");
      out.write("	if (scrollTop < 180) {\r\n");
      out.write("	 scrollTop = 180;\r\n");
      out.write("	}\r\n");
      out.write("	$(\"#followquick\").stop();\r\n");
      out.write("	$(\"#followquick\").animate( { \"top\" : scrollTop });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$(function(){\r\n");
      out.write("		$('#followquick').children().hover(function(){\r\n");
      out.write("			$(this).css({'background-color':'#FBA481', 'color' : '#fff'});\r\n");
      out.write("	}, function(){\r\n");
      out.write("		$(this).css({'background-color':'#11BBFF', 'color' : '#fff'});\r\n");
      out.write("	});\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 상단 스크립트 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		/* 비밀번호 확인하는 메소드 */\r\n");
      out.write("		function checkPw() {\r\n");
      out.write("			var pw1 = document.getElementById('pw1').value;\r\n");
      out.write("			var pw2 = document.getElementById('pw2').value;\r\n");
      out.write("			var check = document.getElementById('check');\r\n");
      out.write("\r\n");
      out.write("			if (pw2 == '' || pw2.length == 0) {\r\n");
      out.write("				check.innerHTML = '';\r\n");
      out.write("			} else if (pw1 != pw2) {\r\n");
      out.write("				check.style.color = 'red';\r\n");
      out.write("				check.innerHTML = '비밀번호가 일치하지 않습니다.';\r\n");
      out.write("			} else {\r\n");
      out.write("				check.style.color = 'green';\r\n");
      out.write("				check.innerHTML = '비밀번호가 일치합니다.';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* 체크박스 선택방식 메소드 */\r\n");
      out.write("		function selectAll() {\r\n");
      out.write("			var agree = document.getElementsByName(\"agree\");\r\n");
      out.write("			var all = document.getElementById(\"all\");\r\n");
      out.write("\r\n");
      out.write("			if (document.getElementById(\"all\").checked) {\r\n");
      out.write("				for (var i = 0; i < agree.length; i++) {\r\n");
      out.write("					agree[i].checked = true;\r\n");
      out.write("				}\r\n");
      out.write("			} else {\r\n");
      out.write("				for (var i = 0; i < agree.length; i++) {\r\n");
      out.write("					agree[i].checked = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function selectOne() {\r\n");
      out.write("			var agree = document.getElementsByName(\"agree\");\r\n");
      out.write("			var all = document.getElementById(\"all\");\r\n");
      out.write("			var count = 0;\r\n");
      out.write("\r\n");
      out.write("			for (var i = 1; i < agree.length; i++) {\r\n");
      out.write("				if (agree[i].checked) {\r\n");
      out.write("					count++;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (count != 4) {\r\n");
      out.write("				all.checked = false;\r\n");
      out.write("			} else {\r\n");
      out.write("				all.checked = true;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* 약관동의 필수사항 선택확인 메소드 */\r\n");
      out.write("		function agreee() {\r\n");
      out.write("			var agree = document.getElementsByName(\"agree\");\r\n");
      out.write("\r\n");
      out.write("			for (var i = 1; i < (agree.length) - 1; i++) {\r\n");
      out.write("				if (agree[i].checked == false) {\r\n");
      out.write("					return 1;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			return 2;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* 회원가입시 빠진 항목 확인 메소드 */\r\n");
      out.write("		function enroll() {\r\n");
      out.write("			var userName = document.getElementById('name').value;\r\n");
      out.write("			var userId = document.getElementById('id').value;\r\n");
      out.write("			var userPw1 = document.getElementById('pw1').value;\r\n");
      out.write("			var userPw2 = document.getElementById('pw2').value;\r\n");
      out.write("			var email = document.getElementById('email').value;\r\n");
      out.write("			var email = document.getElementById('email').value;\r\n");
      out.write("			var phone = document.getElementById('phone').value;\r\n");
      out.write("			var post = document.getElementById('post').value;\r\n");
      out.write("			var add1 = document.getElementById('add1').value;\r\n");
      out.write("			var add2 = document.getElementById('add2').value;\r\n");
      out.write("			var agree = document.getElementsByName('agree');\r\n");
      out.write("			\r\n");
      out.write("			var regExp = /^[A-Za-z0-9]{8,15}$/;\r\n");
      out.write("			var phoneRegExp = /^\\d{3}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("			var postRegExp = /^\\d{5}$/;\r\n");
      out.write("			\r\n");
      out.write("			if (userName == '' || userName.length == 0) {\r\n");
      out.write("				alert('이름을 입력해주세요.');\r\n");
      out.write("				document.getElementById('name').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (userId == '' || userId.length == 0) {\r\n");
      out.write("				alert('아이디를 입력해주세요.');\r\n");
      out.write("				document.getElementById('id').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (userPw1 == '' || userPw1.length == 0) {\r\n");
      out.write("				alert('비밀번호를 입력해주세요.');\r\n");
      out.write("				document.getElementById('pw1').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (userPw2 == '' || userPw2.length == 0) {\r\n");
      out.write("				alert('비밀번호 확인을 입력해주세요.');\r\n");
      out.write("				document.getElementById('pw2').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (document.getElementById('check').style.color == 'red' || userPw1 != userPw2) {\r\n");
      out.write("				alert('비밀번호가 일치하지 않습니다.');\r\n");
      out.write("				document.getElementById('pw2').value = '';\r\n");
      out.write("				document.getElementById('pw2').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!regExp.test(userPw1)) {\r\n");
      out.write("				alert('비밀번호가 조건에 맞지 않습니다');\r\n");
      out.write("				document.getElementById('pw1').value = '';\r\n");
      out.write("				document.getElementById('pw2').value = '';\r\n");
      out.write("				document.getElementById('pw1').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (email == '' || email.length == 0) {\r\n");
      out.write("				alert('이메일을 입력해주세요.');\r\n");
      out.write("				document.getElementById('email').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if(post == '' || post.length == 0) {\r\n");
      out.write("				alert('우편번호를 입력해주세요.');\r\n");
      out.write("				document.getElementById('post').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if(!postRegExp.test(post)) {\r\n");
      out.write("				alert('우편번호는 숫자 5자리 입니다');\r\n");
      out.write("				document.getElementById('post').value = '';\r\n");
      out.write("				document.getElementById('post').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if(add1 == '' || add1.length == 0) {\r\n");
      out.write("				alert('주소를 입력해주세요.');\r\n");
      out.write("				document.getElementById('add1').focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if(add2 == '' || add2.length == 0) {\r\n");
      out.write("				alert('상세주소를 입력해주세요.');\r\n");
      out.write("				document.getElementById('add2').focus();\r\n");
      out.write("				return false;				\r\n");
      out.write("			} else if (agreee() == 1) {\r\n");
      out.write("				alert(\"필수 항목에 동의해주세요.\")\r\n");
      out.write("				return false;\r\n");
      out.write("			} else {\r\n");
      out.write("				alert(userName + \"님, 회원가입이 성공적으로 완료되었습니다.\");\r\n");
      out.write("				return true;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function idCheck() {\r\n");
      out.write("			window.open('checkIdForm.me', 'idCheckForm', 'width=350, height=300');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function emailCheck() {\r\n");
      out.write("			window.open('checkEmailForm.me', 'emailCheckForm', 'width=350, height=300');\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
