/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-20 00:12:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class accessTerms_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/board/../common/top.jsp", Long.valueOf(1624000707607L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/bottom.jsp", Long.valueOf(1623794146328L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하단_이용약관</title>\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap-4.3.1.js\"></script>\r\n");
      out.write("<link href=\"css/bootstrap-4.3.1.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("/* ----------스크롤시 하단아이콘  보이기 --------------------------------------------------------------------- */\r\n");
      out.write("\r\n");
      out.write(".bottomNav {position: fixed; font-size:50px; color: #11BBFF;}\r\n");
      out.write(".bottomNav {bottom: -90px;  transition:bottom .2s;}\r\n");
      out.write(".bottomNav.show {bottom: 0; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	<div id=\"main-container\" class=\"container\">\r\n");
      out.write("		");
      out.write('\r');
      out.write('\n');
 
	Member loginUser = (Member) session.getAttribute("loginUser"); 
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>메인페이지</title>\r\n");
      out.write("<!-- --------------------- -->\r\n");
      out.write("<style>\r\n");
      out.write("/*상단 관련 스타일*/\r\n");
      out.write("/*검색창*/\r\n");
      out.write(".btn-outline-secondary {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:hover {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #FBA481;\r\n");
      out.write("	border-color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:focus, .btn-outline-secondary.focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active, .show>.btn-outline-secondary.dropdown-toggle\r\n");
      out.write("	{\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: #11BBFF;\r\n");
      out.write("	border-color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-secondary:not (:disabled ):not (.disabled ):active:focus,\r\n");
      out.write("	.btn-outline-secondary:not (:disabled ):not (.disabled ).active:focus,\r\n");
      out.write("	.show>.btn-outline-secondary.dropdown-toggle:focus {\r\n");
      out.write("	box-shadow: 0 0 0 0 rgba(17, 187, 255, 0);\r\n");
      out.write("}\r\n");
      out.write("/*아이콘 색변경*/\r\n");
      out.write(".i-plain {\r\n");
      out.write("	color: #11BBFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".i-plain:hover {\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("}\r\n");
      out.write("/*메뉴버튼*/\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   top: 100%;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   display: none;\r\n");
      out.write("   float: left;\r\n");
      out.write("   min-width: 250px;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   font-size: 18px;\r\n");
      out.write("   color: black;\r\n");
      out.write("   text-align: left;\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   background-color: #fff;\r\n");
      out.write("   background-clip: padding-box;\r\n");
      out.write("   border: 2px solid rgba(17, 187, 255, 1);\r\n");
      out.write("   border-radius: 0.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("   color: #11bbff;\r\n");
      out.write("}\r\n");
      out.write(".button1{\r\n");
      out.write("	border: 1px solid rgb(17, 187, 255);\r\n");
      out.write("	background-color: rgb(17, 187, 255);\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* ----------------아이콘 호버시 색 바꾸기------------------- */\r\n");
      out.write(".i-side {\r\n");
      out.write("     color: #fff;\r\n");
      out.write(" }\r\n");
      out.write(".i-side:hover {\r\n");
      out.write("     color: #FBA481;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(".side-nav {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".side-nav:hover{\r\n");
      out.write("	color: #FBA481;\r\n");
      out.write("	text-decoration:none !important\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"font-family: 'Nanum Gothic', sans-serif;\">\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- 1행 -->\r\n");
      out.write("		<div class=\"row\" id=\"top-bar\">\r\n");
      out.write("			<!-- 상단 광고 -->\r\n");
      out.write("			<div class=\"col-12\" onclick=\"location.href='프로모션.html';\"\r\n");
      out.write("				style=\"background: #11BBFF; text-align: center; cursor: pointer; line-height: 30px; font-size: 14px; font-weight: bold; color: white;\">\r\n");
      out.write("				더운 여름을 시원하게! 여름 맞이 프로모션으로 함께 떠나요!</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 2행 -->\r\n");
      out.write("		<div class=\"row\" id=\"secondRow\">\r\n");
      out.write("			<!-- 로고  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<div id=\"logo\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/mainPage.me';\"\r\n");
      out.write("					style=\"color: #11BBFF; font-size: 32px; text-align: center; vertical-align: middle; margin-top: 16px; font-weight: bold; cursor: pointer; color: #11BBFF;\">\r\n");
      out.write("					<i class=\"bi bi-house\" style=\"font-size: 37px;\"></i>다나와방\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 검색창  -->\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<!-- 검색 아이콘  -->\r\n");
      out.write("				<div style=\"margin-top: 30px;\">\r\n");
      out.write("					<input type=\"text\" class=\"form-control\" placeholder=\"검색어를 입력해주세요\" \r\n");
      out.write("						style=\"font-size: 14px; border:2px solid #11bbff; margin-left: 30px;\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<button class=\"btn btn-outline-secondary\" type=\"submit\"\r\n");
      out.write("					id=\"main-search\" style=\"font-size: 14px; margin-top: 30px;\">검색</button>\r\n");
      out.write("			</div>		\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("			<!-- 로그인/회원가입 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"login\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그인/회원가입</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("			<!-- 로그아웃 아이콘 -->\r\n");
      out.write("			<div class=\"col-2\">\r\n");
      out.write("				<div id=\"logout\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/logout.me';\"\r\n");
      out.write("					style=\"width: 140px; margin-left: 10px; font-size: 15px; margin-top: 37px; border-radius: 15px 15px 15px 15px; border-width: 2px 2px 2px 2px; border-style: solid; border-color: #11BBFF; background-color: #11BBFF; color: white; text-align: center; cursor: pointer; font-weight: bold;\">로그아웃</div>\r\n");
      out.write("			</div>	\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("			<!-- 마이페이지 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 42px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("ADMIN")) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/adminMember.me';\"></i>\r\n");
      out.write("			");
 } else {
      out.write("\r\n");
      out.write("				<i class=\"bi bi-person i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/myOrder.me';\"></i>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 고객센터 아이콘  -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 20px; cursor: pointer; font-size: 37px;\">\r\n");
      out.write("				<i class=\"bi bi-headset i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 장바구니 아이콘 -->\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-top: 18px; cursor: pointer; font-size: 38px;\">\r\n");
      out.write("			");
 if(loginUser == null) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/loginForm.me';\"></i>\r\n");
      out.write("			");
 } else if (loginUser != null && loginUser.getIsAdmin().equals("USER")) { 
      out.write("\r\n");
      out.write("				<i class=\"bi bi-cart2 i-plain\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/????????';\"></i>\r\n");
      out.write("			");
 } 
      out.write("	\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 3행 -->\r\n");
      out.write("		<!-- 메뉴아이콘 -->\r\n");
      out.write("		<div class=\"row\" id=\"thirdRow\"\r\n");
      out.write("			style=\"text-align: center; margin-top: 15px;\">\r\n");
      out.write("			<div class=\"col-1\">\r\n");
      out.write("				<div class=\"dropdown\" style=\"margin-top: -10px;\">\r\n");
      out.write("					<a class=\"btn-group-vertical\" href=\"#\" role=\"button\"\r\n");
      out.write("						id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("						aria-expanded=\"false\"><i class=\"bi bi-list i-plain\"\r\n");
      out.write("						style=\"font-size: 35px;\"></i></a>\r\n");
      out.write("					<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\"\r\n");
      out.write("						style=\"text-align: center; font-weight: bold;\">\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">6평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/6평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">8평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/8평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">10평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/10평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">12평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/12평.png\"></a></li>\r\n");
      out.write("						<li class=\"dropdown-item\" style=\"font-weight: bold;\">14평<a\r\n");
      out.write("							class=\"dropdown-item\" href=\"스토어페이지.html\"><img\r\n");
      out.write("								src=\"images/14평.png\"></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 스토어 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='스토어페이지(완).html';\"\r\n");
      out.write("				style=\"font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">스토어</div>\r\n");
      out.write("			<!-- 셀프가이드 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='셀프가이드(완).html';\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">셀프가이드</div>\r\n");
      out.write("			<!-- 프로모션 카테고리 -->\r\n");
      out.write("			<div class=\"col-2\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardPromotion.bo'\"\r\n");
      out.write("				style=\"text-align: center; font-size: 23px; color: #11BBFF; font-weight: bold; cursor: pointer\">프로모션</div>\r\n");
      out.write("			<div class=\"col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 구분선 -->\r\n");
      out.write("		<div\r\n");
      out.write("			style=\"margin-top: 20px; width: 100%; border-bottom: 2px solid #11BBFF; margin-bottom: 15px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 행 사이 빈공간-->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 15px;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<!-- ------------------------스크립트 공간 ----------------------- -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- 상단 스크립트 -->\r\n");
      out.write("	<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#top-bar').children().hover(function() {\r\n");
      out.write("			$(this).css({'background-color' : '#FBA481'});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({'background-color' : '#11BBFF'});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로고\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#logo').hover(function() {\r\n");
      out.write("			$(this).css({'font-size' : '34px', 'color' : '#FBA481'});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({'font-size' : '32px', 'color' : '#11bbff'});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로그인\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#login').hover(function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#FBA481',\r\n");
      out.write("				'border-color' : '#FBA481'\r\n");
      out.write("			});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#11BBFF',\r\n");
      out.write("				'border-color' : '#11BBFF'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//2행 로그아웃\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#logout').hover(function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#FBA481',\r\n");
      out.write("				'border-color' : '#FBA481'\r\n");
      out.write("			});\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css({\r\n");
      out.write("				'background-color' : '#11BBFF',\r\n");
      out.write("				'border-color' : '#11BBFF'\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	//3행\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$('#thirdRow').children().hover(function() {\r\n");
      out.write("			$(this).css('color', '#FBA481');\r\n");
      out.write("		}, function() {\r\n");
      out.write("			$(this).css('color', '#11BBFF');\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 필요한 외부 script -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"\r\n");
      out.write("		integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\"\r\n");
      out.write("		integrity=\"sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!상단 끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("			\r\n");
      out.write("			<!-- 이용약관 제목 -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- 여백 -->\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("				<!-- 이용약관 -->\r\n");
      out.write("				<div class=\"col\"\r\n");
      out.write("					style=\"text-align: center; font-size: 25px; font-weight: bold; color: rgb(17, 187, 255);\">이용약관</div>\r\n");
      out.write("				<!-- 여백 -->\r\n");
      out.write("				<div class=\"col\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 행 사이 빈공간-->\r\n");
      out.write("			<div class=\"row\" style=\"margin-top: 10px;\"></div>\r\n");
      out.write("			<!-- 행 사이 빈공간-->\r\n");
      out.write("			<div class=\"row\" style=\"margin-top: 30px;\"></div>\r\n");
      out.write("			<!-- 본문내용 -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 overflow-auto\" style=\"font-size: 12px;\">\r\n");
      out.write("					<b>제 1조 (목적)</b><br>\r\n");
      out.write("					<br> 다나와방 서비스 이용약관(이하 “약관”이라 합니다)은 (주)다나와방(이하 “회사”라 합니다)이 제공하는\r\n");
      out.write("					서비스와 관련하여 회사와 이용 고객(또는 회원) 간에 서비스의 이용 조건 및 절차, 회사와 회원 간의 권리, 의무 및\r\n");
      out.write("					책임 사항 기타 필요한 사항을 규정함을 목적으로 합니다.<br>\r\n");
      out.write("					<br> <b>제 2조 (용어)</b><br>\r\n");
      out.write("					<br>본 약관에서 사용하는 용어의 정의는 다음 각 호와 같으며, 정의되지 않은 용어에 대한 해석은 관계법령 및\r\n");
      out.write("					서비스별 안내에서 정하는 바에 따릅니다.<br>\r\n");
      out.write("					<br>1. 다나와방 서비스(이하 “서비스”라 합니다): 이용 고객 또는 회원이 PC, 휴대형 단말기,\r\n");
      out.write("					태블릿PC 등 각종 유무선 기기 또는 프로그램을 통하여 이용할 수 있도록 회사가 제공하는 인테리어 관련 컨텐츠 및 전문가\r\n");
      out.write("					큐레이션 서비스, SNS 및 그 외 관련된 서비스를 말합니다.<br>2. 회원: 회사의 서비스에 접속하여 본\r\n");
      out.write("					약관에 동의하고 ID와 PASSWORD를 발급 받았으며 회사가 제공하는 서비스를 이용하는 고객을 포괄적으로 의미합니다.<br>3.\r\n");
      out.write("					전문가: 인테리어 관련 서비스나 제품을 판매하는 직종에 종사하는 회원 중 회사가 지정한 절차 및 검수를 마치고 해당\r\n");
      out.write("					회원의 서비스와 제품에 대한 정보 및 상담을 제공할 수 있는 회원을 의미합니다. 본 약관에서 별도로 전문가를 언급하지\r\n");
      out.write("					않는 경우에는 모든 약관의 조항들이 전문가에게도 회원과 동일하게 적용됩니다.<br>4. 회원정보: 회사가\r\n");
      out.write("					가입신청자에게 회원가입 신청양식(이하 “신청양식\"이라 합니다)에 기재를 요청하는 가입신청자의 개인정보와 회원의 식별과\r\n");
      out.write("					서비스 이용을 위하여 회원이 입력하고 서비스 내 공개된 개인정보를 의미합니다.<br>5. 전문가 정보: 전문가가\r\n");
      out.write("					되기 위해 회사가 지정한 절차 및 검수 과정에서 기재하는 전문가의 정보를 의미합니다.<br>6.\r\n");
      out.write("					ID(고유번호): 회원 식별과 회원의 본 서비스 이용을 위하여 회원이 선정하고 회사가 승인하는 문자와 숫자의 조합을\r\n");
      out.write("					말합니다. 본 서비스에서는 E-mail 주소를 ID로 사용합니다.<br>7. PASSWORD(비밀번호): 회원의\r\n");
      out.write("					정보 보호를 위해 회원 자신이 설정한 문자와 숫자의 조합을 말합니다.<br>8. 게시물: 회원이 회사가 제공하는\r\n");
      out.write("					서비스에 게시 또는 등록하는 부호(URL 포함), 문자, 음성, 음향, 영상(동영상 포함), 이미지(사진 포함), 파일\r\n");
      out.write("					등 일체의 정보를 말합니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제3조 (약관의 효력 및 변경)</b><br>\r\n");
      out.write("					<br>① 본 약관은 회원이 쉽게 알 수 있도록 서비스 내 또는 연결화면을 통하여 게시하거나 기타의 방법으로\r\n");
      out.write("					회원에게 공지함으로써 효력이 발생합니다.<br>② 회사는 약관의 규제에 관한 법률, 정보통신망 이용촉진 및\r\n");
      out.write("					정보보호 등에 관한 법률 등 관계법령에 위배되지 않는 범위 내에서 본 약관을 개정할 수 있습니다.<br>③\r\n");
      out.write("					회사는 약관을 개정할 경우 그 개정이유 및 적용일자를 명시하여 현행 약관과 함께 적용일자 7일전부터 적용일 전일까지\r\n");
      out.write("					제1항의 방법으로 공지합니다. 다만, 회원의 권리 또는 의무에 관한 중요한 규정의 변경은 최소한 30일전에 공지하고\r\n");
      out.write("					개정약관을 회원이 등록한 E-mail로 발송하여 통지합니다.<br>④ 회사가 제3항에 따라 개정약관을 공지 또는\r\n");
      out.write("					통지하였음에도 불구하고 회원이 명시적으로 거부의사를 표시하지 아니하는 경우 회원이 개정약관에 동의한 것으로 봅니다.<br>⑤\r\n");
      out.write("					회원은 변경된 약관에 동의하지 아니하는 경우 서비스의 이용을 중단하고 이용계약을 해지할 수 있습니다.<br>⑥\r\n");
      out.write("					본 약관에 동의하는 것은 서비스를 정기적으로 방문하여 약관의 변경사항을 확인하는 것에 동의함을 의미합니다. 변경된 약관에\r\n");
      out.write("					대한 정보를 알지 못하여 발생하는 회원의 피해에 대하여 회사는 책임을 지지 않습니다. <br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제4조 (약관 외 준칙)</b><br>\r\n");
      out.write("					<br>본 약관에 명시되지 않은 사항에 대해서는 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 약관의 규제에\r\n");
      out.write("					관한 법률, 전기통신사업법 등 관계법령 및 회사가 정한 서비스의 세부이용지침 등의 규정에 따릅니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제5조 (이용계약의 성립)</b><br>\r\n");
      out.write("					<br> ① 서비스 이용계약은 회사가 정한 가입 양식에 따라 회원정보(전자우편주소, 비밀번호, 별명 등)를\r\n");
      out.write("					기입하여 회원가입신청을 하고 회사가 이러한 신청에 대하여 승인함으로써 체결됩니다.<br>② 전문가 전환의\r\n");
      out.write("					경우에는 인테리어 관련 서비스나 제품을 판매하는 직종에 종사하는 회원이 회사가 정한 절차에 따라 정보를 기입하여 전문가\r\n");
      out.write("					전환 신청을 하고 회사가 해당 전문가 전환 신청을 승인하면 전문가로서 서비스를 이용할 수 있습니다.<br>③\r\n");
      out.write("					가입신청자가 회원정보를 제출하는 것은 회원가입 화면에 노출되어 있는 본 약관 및 개인정보처리방침의 내용을 숙지하고,\r\n");
      out.write("					회사가 서비스 이용을 위해 운영하는 각종 정책(저작권 정책, 운영 방침 등)과 수시로 공지하는 사항을 준수하는 것에 대해\r\n");
      out.write("					동의하는 것으로 봅니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제6조 (이용신청에 대한 승낙 및 제한)</b><br>\r\n");
      out.write("					<br>① 회사는 서비스의 이용을 신청한 가입신청자에 대하여 업무상ㆍ기술상 지장이 없는 한 접수순서에 따라\r\n");
      out.write("					서비스의 이용을 승낙합니다.<br>② 타인의 개인정보를 도용하는 등 부정한 목적 또는 방법으로 이용신청을 한\r\n");
      out.write("					회원의 ID는 사전 통지 없이 이용 계약이 해지될 수 있으며, 당해 회원은 관계법령에 따라 처벌을 받을 수 있습니다.<br>③\r\n");
      out.write("					회사는 다음 각 호에 해당하는 이용신청에 대하여는 승낙을 하지 않을 수 있습니다.<br>1. 기술상 서비스\r\n");
      out.write("					제공이 불가능한 경우 <br>2. 신청양식의 기재사항을 누락하거나 오기하여 신청하는 경우 <br>3.\r\n");
      out.write("					사회의 안녕질서 또는 미풍양속을 저해하거나 저해할 목적으로 신청한 경우 <br>4. 회원의 귀책사유에 의하여\r\n");
      out.write("					회원자격을 상실한 적이 있는 경우. 다만, 자격상실 이후 6개월 이상 경과한 자로 회사의 회원 재가입 승낙을 받은 경우는\r\n");
      out.write("					예외로 합니다.<br>5. 기타 회사가 정한 이용요건에 충족되지 않았을 경우 ④ 회사는 서비스를 이용하는 회원에\r\n");
      out.write("					대하여 회원의 종류 및 등급별로 구분하여 이용시간, 이용회수, 서비스 메뉴 등을 세분하여 이용에 차등을 둘 수 있습니다.<br>⑤\r\n");
      out.write("					회사는 전문가 전환을 신청한 회원에 대하여 회사의 업무상ㆍ기술상 또는 서비스 운영정책상 전문가 전환 신청을 승낙하지 않을\r\n");
      out.write("					수 있습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제7조 (회원정보의 변경)</b><br>\r\n");
      out.write("					<br>① 회원은 서비스를 통하여 언제든지 본인의 개인정보를 열람하고 수정할 수 있습니다. <br>②\r\n");
      out.write("					회원은 서비스를 이용하면서 회사에 제출한 회원정보가 변경되었을 경우 개인정보 설정 화면에서 회원정보를 수정하거나\r\n");
      out.write("					고객센터를 통하여 회사에 변경 사항을 통지하여야 합니다.<br>③ 회원정보를 수정하지 않음으로 인하여 발생하는\r\n");
      out.write("					모든 책임은 회원에게 있습니다.<br>④ 전문가가 회사에 제출한 전문가 정보를 변경했을 경우, 회사가 실시하는\r\n");
      out.write("					변경된 정보에 대해 검수를 통과해야만 변경된 정보가 서비스에 반영됩니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제8조 (서비스의 이용)</b><br>\r\n");
      out.write("					<br>① 회사는 회원의 이용신청을 승낙한 때부터 서비스를 개시합니다.<br>② 회사의 업무상ㆍ기술상의\r\n");
      out.write("					장애로 인하여 서비스를 개시하지 못하는 경우에는 서비스에 공지하거나 회원에게 이를 통지합니다.<br>③ 서비스의\r\n");
      out.write("					이용은 연중무휴 1일 24시간을 원칙으로 합니다. 다만, 회사의 업무상ㆍ기술상 또는 서비스 운영정책상 서비스가 일시\r\n");
      out.write("					중지될 수 있습니다. 이러한 경우 회사는 사전 또는 사후에 이를 공지합니다.<br>④ 회사는 서비스를 일정범위로\r\n");
      out.write("					분할하여 각 범위 별로 이용 가능한 시간을 별도로 정할 수 있으며 이 경우 그 내용을 공지합니다.<br>⑤\r\n");
      out.write("					회사는 서비스 내의 개별서비스에 대한 별도의 약관을 둘 수 있으며, 개별서비스에서 별도로 적용되는 약관에 대한 동의는\r\n");
      out.write("					회원이 개별서비스를 최초로 이용할 경우 별도의 동의절차를 거치게 됩니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제9조 (서비스의 변경 및 중지)</b><br>\r\n");
      out.write("					<br> ① 회사는 서비스(개별서비스 포함)를 변경하여야 하는 상당한 이유가 있는 경우 변경될 서비스의 내용 및\r\n");
      out.write("					제공일자를 제15조에서 정한 방법으로 회원에게 통지하고 서비스를 변경하여 제공할 수 있습니다.<br>② 회사는\r\n");
      out.write("					다음 각 호에 해당하는 경우 서비스의 전부 또는 일부를 제한하거나 중지할 수 있습니다.<br>1. 서비스용\r\n");
      out.write("					설비의 보수 등 공사로 인한 부득이한 경우<br> 2. 회원이 회사의 영업활동을 방해하는 경우<br>3.\r\n");
      out.write("					정전, 제반 설비의 장애 또는 이용량의 폭주 등으로 정상적인 서비스 이용에 지장이 있는 경우 <br>4.\r\n");
      out.write("					제휴업체(BP)와의 계약종료 등과 같은 회사의 제반 사정으로 서비스를 유지할 수 없는 경우 <br>5. 기타\r\n");
      out.write("					천재지변, 국가비상사태 등 불가항력적 사유가 있는 경우<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제10조 (정보의 제공 및 광고의 게재)</b><br>\r\n");
      out.write("					<br>① 회사는 서비스를 운영함에 있어 각종 정보를 서비스 화면에 게재하거나 E-mail, 서신우편,\r\n");
      out.write("					SMS(MMS)등으로 회원에게 제공할 수 있습니다.<br>② 회사는 서비스를 운영함에 있어 회사 또는 제휴사의\r\n");
      out.write("					서비스 관련 각종 광고를 서비스 화면 또는 게시물과 결합하여 게재하거나 회원의 동의를 얻어 E-mail 및 서신 우편,\r\n");
      out.write("					SMS(MMS) 등의 방법으로 회원에게 제공할 수 있습니다.<br>③ 회원이 서비스상에 게재되어 있는 광고를\r\n");
      out.write("					이용하거나 서비스를 통한 광고주의 판촉활동에 참여하는 등의 방법으로 교신 또는 거래를 하는 것은 전적으로 회원과\r\n");
      out.write("					광고주간의 문제입니다. 만약, 회원과 광고주간에 문제가 발생할 경우에도 회원과 광고주가 직접 해결하여야 하며, 이와\r\n");
      out.write("					관련하여 회사는 어떠한 책임도 지지 않습니다.<br>④ 회사는 다음 각호에 해당하는 경우 회원의 동의여부와\r\n");
      out.write("					상관없이 전자우편으로 발송할 수 있습니다.<br>1. 이용 신청에서 입력한 전자우편 주소의 소유를 확인하기\r\n");
      out.write("					위해서 인증메일을 발송하는 경우<br>2. 회원의 정보가 변경되어 확인하기 위해서 인증메일을 발송하는 경우<br>3.\r\n");
      out.write("					기타 서비스를 제공함에 있어 회원이 반드시 알아야 하는 중대한 정보라고 회사가 판단하는 경우<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b> 제11조 (회사의 의무)</b> <br>\r\n");
      out.write("					<br> ① 회사는 서비스 제공과 관련하여 알고 있는 회원의 회원정보를 본인의 동의 없이 제3자에게 제공하지\r\n");
      out.write("					않습니다.<br>② 회사는 회원의 회원정보를 보호하기 위해 보안시스템을 구축 운영하며, \"개인정보처리방침\"을\r\n");
      out.write("					공지하고 준수합니다. 또한, 회사는 \"개인정보처리방침\"에 따라 회원정보를 처리함에 있어 안정성 확보에 필요한 기술적 및\r\n");
      out.write("					관리적 대책을 수립ㆍ운영합니다.<br>③ 회사는 서비스와 관련한 회원의 불만사항이 접수되는 경우 이를 신속하게\r\n");
      out.write("					처리하여야 하며, 신속한 처리가 곤란한 경우 그 사유와 처리 일정을 서비스 화면에 게재하거나 E-mail 등을 통하여\r\n");
      out.write("					회원에게 통지합니다.<br>④ 회사가 제공하는 서비스로 인하여 회원에게 손해가 발생한 경우 그러한 손해가 회사의\r\n");
      out.write("					고의나 중과실에 의해 발생한 경우에 한하여 회사에서 책임을 부담하며, 그 책임의 범위는 통상손해에 한합니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제12조 (회원의 의무)</b><br>\r\n");
      out.write("					<br>① 회원은 관계법령, 약관, 서비스 이용안내 및 서비스상에 공지한 주의사항, 회사가 서비스 이용과\r\n");
      out.write("					관련하여 회원에게 통지하는 사항 등을 준수하여야 하며, 기타 회사의 업무에 방해되는 행위를 하여서는 아니 됩니다.<br>②\r\n");
      out.write("					회원은 회사에서 공식적으로 인정한 경우를 제외하고는 서비스를 이용하여 상품을 판매하는 영업 활동을 할 수 없으며, 특히\r\n");
      out.write("					해킹, 광고를 통한 수익, 음란사이트를 통한 상업행위, 상용소프트웨어 불법배포 등을 할 수 없습니다. 이를 위반하여\r\n");
      out.write("					발생한 영업 활동의 결과 및 손실, 관계기관에 의한 구속 등 법적 조치 등에 관해서는 회사가 책임을 지지 않으며, 회원은\r\n");
      out.write("					이와 같은 행위와 관련하여 회사에 대하여 손해배상 의무를 집니다.<br>③ 회원은 서비스의 이용권한, 기타\r\n");
      out.write("					서비스 이용계약상의 지위를 타인에게 양도, 증여할 수 없으며 이를 담보로 제공할 수 없습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제13조 (회원에 대한 통지)</b><br>\r\n");
      out.write("					<br>① 회사는 회원의 서비스 이용에 필요한 권리 및 의무 등에 관한 사항을 회원이 지정한 E-mail,\r\n");
      out.write("					SMS 등으로 통지할 수 있습니다.<br>② 회사는 불특정 다수 회원에 대한 통지의 경우 서비스에 게시함으로써\r\n");
      out.write("					개별 통지에 갈음할 수 있습니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제14조 (ID와 PASSWORD 관리에 대한 의무와 책임)</b><br>\r\n");
      out.write("					<br> ① 회원은 자신의 ID와 PASSWORD 관리를 철저히 하여야 합니다. ID와 PASSWORD의 관리\r\n");
      out.write("					소홀, 부정 사용에 의하여 발생하는 모든 결과에 대한 책임은 회원 본인에게 있습니다.<br>② 회사\"는 회원\r\n");
      out.write("					ID의 유출 우려가 있거나, 반사회적 또는 미풍양속에 어긋나거나 회사 및 회사의 운영자로 오인할 우려가 있는 경우, 해당\r\n");
      out.write("					ID의 이용을 제한할 수 있습니다.<br>③ 회원은 본인의 ID 및 PASSWORD를 타인에게 이용하게 해서는\r\n");
      out.write("					안되며, 회원 본인의 ID 및 PASSWORD를 도난 당하거나 타인이 사용하고 있음을 인지하는 경우에는 바로 회사에\r\n");
      out.write("					통보하고 회사의 안내가 있는 경우 그에 따라야 합니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제15조 (회원정보의 보호 및 이용)</b><br>\r\n");
      out.write("					<br>① 회사는 적법하고 공정한 수단에 의하여 이용계약의 성립 및 이행에 필요한 최소한의 범위 내에서\r\n");
      out.write("					개인정보처리방침에 따라 회원의 회원정보를 수집합니다.<br>② 회사의 개인정보처리방침은 회사에 연동된 다른\r\n");
      out.write("					서비스(회사가 운영하지 않는 서비스를 말합니다. 이하 같습니다)에는 적용되지 않습니다.<br>③ 회사는\r\n");
      out.write("					통신비밀보호법, 정보통신망 이용촉진 및 정보보호 등에 관한 법률 등 관계법령에 따라 행정기관이나 수사기관 등에서 회원의\r\n");
      out.write("					회원정보의 열람이나 제출을 요청하는 경우에는 이를 제공할 수 있습니다.<br>④ 회사는 회원의 귀책사유로 인해\r\n");
      out.write("					노출된 회원정보에 대해서 일체의 책임을 부담하지 않습니다.<br>⑤ 회사는 회원정보의 처리 및 관리 등의 업무를\r\n");
      out.write("					스스로 수행함을 원칙으로 하나, 필요한 경우 이러한 업무의 일부 또는 전부를 회사가 선정한 회사에 위탁할 수 있으며,\r\n");
      out.write("					회원정보의 처리 및 관리 등에 관한 업무를 위탁하는 경우에는 개인정보처리방침을 통하여 공지합니다.<br>⑥\r\n");
      out.write("					회원이 이용계약 체결과정에서 회사에 제공한 회원정보에 대한 이용 또는 제공에 대한 동의를 철회하고자 하는 경우에는\r\n");
      out.write("					개인정보처리방침에서 정한 바에 따르며, 회원이 이러한 동의를 철회하는 경우 서비스 이용계약은 자동으로 해지됩니다.<br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<b>제 16조 (분쟁 조정 및 관할법원)</b><br>\r\n");
      out.write("					<br> ① 서비스 이용과 관련하여 회사와 회원 사이에 분쟁이 발생한 경우, 회사와 회원은 분쟁의 해결을 위해\r\n");
      out.write("					성실히 협의합니다.<br>② 본 조 제1항의 협의에서도 분쟁이 해결되지 않을 경우 양 당사자는 민사소송법상의\r\n");
      out.write("					관할법원에 소를 제기할 수 있습니다.<br>③ 회사와 이용자간에 제기된 소송에는 대한민국 법을 적용합니다.<br>④\r\n");
      out.write("					본 약관은 한글로 작성되었습니다. 본 약관의 번역본이 한글 원문과 차이가 있을 경우 한글 원문이 우선합니다.<br>⑤\r\n");
      out.write("					본 조 제1항의 협의에서도 분쟁이 해결되지 않아 소송이 제기되는 경우에는 “회사”의 본사 소재지를 관할하는 법원을 전속\r\n");
      out.write("					관할법원으로 합니다. 부칙 (시행일) 본 약관은 2021년 7월 6일부터 시행합니다. 종전 약관은 본 약관으로\r\n");
      out.write("					대체됩니다. 개정된 이용약관의 적용일자 이전 가입자 또한 개정된 이용약관의 적용을 받습니다.\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 40px;\">\r\n");
      out.write("			<div class=\"col-1\"></div>\r\n");
      out.write("			<div class=\"col-4\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardFaq.bo';\"\r\n");
      out.write("				style=\"color: black; font-size: 22px; font-weight: bold; cursor: pointer; line-height:20px; margin-left: 20px; margin-bottom:-10px;\">\r\n");
      out.write("				고객센터 : 1555-5551<br><span style=\"font-size: 13px; font-weight: normal; color:black;\">평일 09:00 ~ 18:00 (주말 & 공휴일 제외)</span></div>\r\n");
      out.write("			<div class=\"col-6\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 20px; color: black; line-height: 20px; font-size: 13px; font-weight: bold; cursor: pointer;\">\r\n");
      out.write("			<div class=\"col-1\" style=\"margin-right:-20px;\"></div>\r\n");
      out.write("			<div class=\"col-6\">\r\n");
      out.write("			<div class=\"row\" style=\"margin:auto; text-align: center;\">\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/introduction.me';\">회사소개</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/accessTerms.me';\">이용약관</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/privacyPolicy.me';\">개인정보처리방침</div>\r\n");
      out.write("				<div class=\"col\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/boardNotice.bo';\">공지사항</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-5\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\" style=\"margin-top: 10px; margin-left: 10px; font-size: 12px;\">\r\n");
      out.write("			<div class=\"col-1\"></div>\r\n");
      out.write("			<div class=\"col-11\">\r\n");
      out.write("				<p>\r\n");
      out.write("					상호명 : (주)다나와방 / 이메일 : danawabang@danawabang.com / 대표이사 : 박신우 /\r\n");
      out.write("					사업자등록번호 : 999-88-77777 / 통신판매업신고번호 : 제2021-서울역삼-0215호<br> 주소 :\r\n");
      out.write("					서울 역삼구 역삼대로56길 6 타워팰리스타워 31층 <br> Copyright 2021. danawabang,\r\n");
      out.write("					Co., Ltd. All rights reserved\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!하단 끝 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- 탭 하면 맨위로 올라가는 버튼 -->				 \r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-10\"></div>\r\n");
      out.write("		<div class=\"col-1\" style=\"float-right\">\r\n");
      out.write("			<i class=\"bi bi-arrow-up-circle-fill bottomNav i-plain\" \r\n");
      out.write("			style=\"cursor:pointer;\" onclick=\"window.scrollTo(0,0);\" ></i>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-1\">\r\n");
      out.write("			<i class=\"bi bi-whatsapp bottomNav i-plain\" style=\"cursor:pointer;\" ></i>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- 스크롤 시 하단 아이콘 보이기-------------------------------------------- -->\r\n");
      out.write("	<script>\r\n");
      out.write("	//Javascript\r\n");
      out.write("	var lastScrollTop = 0;\r\n");
      out.write("	var delta = 10;\r\n");
      out.write("	var fixBox = document.querySelector('.bottomNav');\r\n");
      out.write("	var fixBoxHeight = fixBox.offsetHeight;\r\n");
      out.write("	var didScroll;\r\n");
      out.write("	//스크롤 이벤트 \r\n");
      out.write("	window.onscroll = function(e) {\r\n");
      out.write("	    didScroll = true;\r\n");
      out.write("	};\r\n");
      out.write("\r\n");
      out.write("	//0.25초마다 스크롤 여부 체크하여 스크롤 중이면 hasScrolled() 호출\r\n");
      out.write("	setInterval(function(){\r\n");
      out.write("	    if(didScroll){\r\n");
      out.write("	        hasScrolled();\r\n");
      out.write("	        didScroll = false;\r\n");
      out.write("	    }\r\n");
      out.write("	}, 250);\r\n");
      out.write("\r\n");
      out.write("	function hasScrolled(){\r\n");
      out.write("	    var nowScrollTop = window.scrollY;\r\n");
      out.write("	    if(Math.abs(lastScrollTop - nowScrollTop) <= delta){\r\n");
      out.write("	        return;\r\n");
      out.write("	    }\r\n");
      out.write("	    if(nowScrollTop > lastScrollTop && nowScrollTop > fixBoxHeight){\r\n");
      out.write("	        //Scroll down\r\n");
      out.write("	        fixBox.classList.add('show');\r\n");
      out.write("	    }else{\r\n");
      out.write("	        if(nowScrollTop + window.innerHeight < document.body.offsetHeight){\r\n");
      out.write("	            //Scroll up\r\n");
      out.write("	            fixBox.classList.remove('show');\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("	    lastScrollTop = nowScrollTop;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
